import { pathToFileURL } from 'node:url';
import { CTraderJsonSession } from '../src/adapters/ctrader_session.js';
import { ctraderEndpoint } from '../src/adapters/ctrader_protocol.js';
import { createCTraderSourceCapture } from '../src/sources/nontelegram/ctrader_source_capture.js';
import { createSignedV1SourceClient } from '../src/sources/nontelegram/signed_v1_client.js';
import { createNonTelegramSourceRuntime } from '../src/sources/nontelegram/source_runtime.js';

const REQUIRED = [
  'GATE6_CTRADER_CLIENT_ID',
  'GATE6_CTRADER_CLIENT_SECRET',
  'GATE6_CTRADER_ACCESS_TOKEN',
  'GATE6_CTRADER_ACCOUNT_ID',
  'GATE6_CTRADER_SOURCE_ENDPOINT',
  'GATE6_CTRADER_SOURCE_ID',
  'GATE6_CTRADER_SOURCE_SECRET',
];

function text(value) {
  return String(value ?? '').trim();
}

function requireEnvironment(env = process.env) {
  if (text(env.BROKER_EXECUTION_ENABLED).toLowerCase() !== 'false') {
    throw new Error('GATE6_BROKER_EXECUTION_MUST_BE_FALSE');
  }
  const missing = REQUIRED.filter((name) => !text(env[name]));
  if (missing.length) throw new Error(`GATE6_SOURCE_CONFIG_MISSING:${missing.join(',')}`);
  const accountId = Number(env.GATE6_CTRADER_ACCOUNT_ID);
  if (!Number.isInteger(accountId)) throw new Error('GATE6_CTRADER_ACCOUNT_INVALID');
  return { accountId };
}

function boundedMs(value, fallback, min = 1000, max = 300000) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.max(min, Math.min(max, Math.trunc(number)));
}

function duplicateResult(result = {}) {
  return result?.duplicate === true
    || String(result?.status ?? '').toUpperCase() === 'DUPLICATE'
    || String(result?.code ?? '').toUpperCase().includes('DUPLICATE');
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function openDemoSourceSession(env, accountId) {
  const session = new CTraderJsonSession({
    endpoint: ctraderEndpoint('demo', 'json'),
    clientId: env.GATE6_CTRADER_CLIENT_ID,
    clientSecret: env.GATE6_CTRADER_CLIENT_SECRET,
    requestTimeoutMs: boundedMs(env.GATE6_CTRADER_REQUEST_TIMEOUT_MS, 10000),
  });
  await session.open();
  await session.authenticateAccount(accountId, env.GATE6_CTRADER_ACCESS_TOKEN);
  return session;
}

function createSignedSourceDelivery(env) {
  const client = createSignedV1SourceClient({
    endpoint: env.GATE6_CTRADER_SOURCE_ENDPOINT,
    sourceId: env.GATE6_CTRADER_SOURCE_ID,
    sourceSecret: env.GATE6_CTRADER_SOURCE_SECRET,
  });
  return createNonTelegramSourceRuntime({
    providerType: 'ctrader_source',
    client,
    retryDelaysMs: [250, 1000, 3000],
  });
}

async function waitForCapturedDeal(capture, timeoutMs) {
  const started = Date.now();
  while (Date.now() - started < timeoutMs) {
    const status = capture.status();
    if (status.deliveredEvents > 0) return status;
    await sleep(250);
  }
  throw new Error('GATE6_CTRADER_DEAL_EVENT_NOT_OBSERVED');
}

export async function runGate6CTraderSourceAcceptance({ env = process.env } = {}) {
  const { accountId } = requireEnvironment(env);
  const timeoutMs = boundedMs(env.GATE6_CTRADER_CAPTURE_TIMEOUT_MS, 60000, 5000, 300000);
  const sourceRuntime = createSignedSourceDelivery(env);
  const captured = [];

  let session = await openDemoSourceSession(env, accountId);
  let capture;
  try {
    const observingRuntime = {
      async deliver(sourceEvent) {
        captured.push(structuredClone(sourceEvent));
        return sourceRuntime.deliver(sourceEvent);
      },
    };
    capture = createCTraderSourceCapture({ session, runtime: observingRuntime, accountId });
    capture.start();
    await waitForCapturedDeal(capture, timeoutMs);
    capture.stop();
    await capture.drain();
  } finally {
    capture?.stop?.();
    session.close();
  }

  if (captured.length < 1) throw new Error('GATE6_CTRADER_CAPTURE_EMPTY');

  // Replay the exact captured source event through the signed canonical source
  // delivery. Persistent ingress idempotency, not an in-memory set, must mark it
  // duplicate and prevent a second interpretation/orchestration path.
  const replay = await sourceRuntime.deliver(captured[0]);
  if (!duplicateResult(replay)) throw new Error('GATE6_CTRADER_REPLAY_NOT_DUPLICATE');

  // Reconnect is authenticated independently. No broker order is generated by
  // this runner; the observed demo deal must be prepared independently.
  session = await openDemoSourceSession(env, accountId);
  session.close();

  const captureStatus = capture.status();
  return {
    ok: true,
    provider: 'ctrader_source',
    accountScoped: true,
    deliveredEvents: captureStatus.deliveredEvents,
    failedEvents: captureStatus.failedEvents,
    canonicalReplayDuplicate: true,
    reconnectAuthenticated: true,
    brokerExecutionEnabled: false,
  };
}

async function main() {
  try {
    const result = await runGate6CTraderSourceAcceptance();
    console.log(JSON.stringify(result));
  } catch (error) {
    console.error(JSON.stringify({ ok: false, reason: String(error?.message || 'GATE6_CTRADER_SOURCE_FAILED').split(':')[0] }));
    process.exitCode = 1;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
