export function withEnterpriseConnectionEnhancements(html) {
  const script = `<script>(function(){
function q(id){return document.getElementById(id)}
function safe(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function splitIds(v){return String(v||'').split(/[\\n,]+/).map(function(x){return x.trim()}).filter(Boolean)}
function auth(){return {workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function admin(path,options){options=options||{};var s=auth();if(!s.workspace||!s.bearer)throw new Error('Your session has expired. Sign in again.');var r=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':s.workspace,'Authorization':'Bearer '+s.bearer},options.headers||{})}));var b;try{b=await r.json()}catch(_){b={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||b.ok===false)throw new Error(b.reason||('HTTP_'+r.status));return b}
function note(text,type){var el=q('workspaceMessage');if(!el)return;el.className='notice '+(type||'info');el.textContent=text}
function ensureSourceExtras(){var host=q('sourceFields');if(!host||q('enterpriseSourceExtras'))return;var el=document.createElement('div');el.id='enterpriseSourceExtras';el.style.marginTop='10px';host.insertAdjacentElement('afterend',el);var wrap=host.closest('.card');if(wrap&&!q('enterpriseSourceControls')){var controls=document.createElement('div');controls.id='enterpriseSourceControls';controls.className='formbox';controls.innerHTML='<b>Connected sources</b><div class="muted small">Save a source, then connect it when its configuration is ready.</div><div id="enterpriseSourceControlRows" style="margin-top:8px"></div><div id="externalSourceSetup"></div>';wrap.appendChild(controls)}}
function renderSourceExtras(){ensureSourceExtras();var p=q('sourceProvider')&&q('sourceProvider').value,el=q('enterpriseSourceExtras');if(!el)return;if(p==='external_mtproto')el.innerHTML='<div class="notice info"><b>Customer-hosted Telegram userbot.</b> Telegram login remains on your VM. Mkety receives signed events at <code>/api/v1/events</code>; the adapter needs <code>TRADING_SOURCE_ID</code> and a one-time <code>TRADING_SOURCE_SECRET</code> for HMAC authentication.</div><div class="grid"><div class="field"><label>Telegram account scope</label><input id="sourceTelegramScope" placeholder="client-main-account"></div><div class="field"><label>Chat acceptance</label><select id="sourceChatMode"><option value="allowlist">Only selected chats</option><option value="all_visible">All chats visible to this userbot</option></select></div></div><div class="field" style="margin-top:10px"><label>Allowed chat IDs</label><textarea id="sourceAllowedChats" rows="2" placeholder="-1001234567890, -1009876543210"></textarea><div class="muted small">Authoritative server filter. The external adapter may also use ALLOWED_CHAT_IDS locally to reduce traffic.</div></div>';else if(p==='cloudflare_container_mtproto'||p==='cloudflare_do_mtproto')el.innerHTML='<div class="grid"><div class="field"><label>Telegram account scope</label><input id="sourceTelegramScope" placeholder="hosted-account-1"></div><div class="field"><label>Allowed chat IDs</label><input id="sourceAllowedChats" placeholder="-1001234567890, -1009876543210"></div></div><div class="muted small">Mkety-hosted MTProto monitors only the Telegram chats you list here.</div>';else el.innerHTML=''}
function sourceCredentials(p){if(p==='cloudflare_container_mtproto'||p==='cloudflare_do_mtproto')return{apiId:q('srcApiId').value,apiHash:q('srcApiHash').value,session:q('srcSession').value};if(p==='mt5_source_bridge')return{bridgeUrl:q('srcBridgeUrl').value,bridgeSecret:q('srcBridgeSecret').value};if(p==='ctrader_source'){var x={clientId:q('srcClientId').value,clientSecret:q('srcClientSecret').value,accessToken:q('srcAccessToken').value};if(q('srcRefreshToken').value)x.refreshToken=q('srcRefreshToken').value;return x}return undefined}
function sourceDefinition(p){var map={tradingview_webhook:['tradingview','tradingview_webhook'],custom_signed_api:['custom_api','custom_signed_api'],external_mtproto:['telegram','telegram_mtproto'],cloudflare_container_mtproto:['telegram','telegram_mtproto'],cloudflare_do_mtproto:['telegram','telegram_mtproto'],mt5_source_bridge:['mt5','mt5_source_bridge'],ctrader_source:['ctrader','ctrader_source']};return map[p]}
async function createSourceComplete(ev){ev.preventDefault();ev.stopImmediatePropagation();var p=q('sourceProvider').value,d=sourceDefinition(p),instance=q('sourceInstance').value.trim(),name=q('sourceName').value.trim();if(!instance){note('Reference is required for this source.','error');return}var payload={providerType:p,sourceFamily:d[0],sourceType:d[1],sourceInstanceId:instance,displayName:name||instance,priority:Number(q('sourcePriority').value||0)};if(p.indexOf('mtproto')!==-1){var scope=(q('sourceTelegramScope')&&q('sourceTelegramScope').value.trim())||instance;payload.externalIdentity=scope;var chats=splitIds(q('sourceAllowedChats')&&q('sourceAllowedChats').value);if(p==='external_mtproto'){var mode=(q('sourceChatMode')&&q('sourceChatMode').value)||'allowlist';if(mode==='allowlist'&&!chats.length){note('Choose at least one allowed Telegram chat, or explicitly select All chats visible to this userbot.','error');return}payload.config={chat_acceptance_mode:mode,allowed_chat_ids:chats}}else{if(!chats.length){note('Add at least one Telegram chat ID for the hosted listener.','error');return}payload.config={chat_ids:chats}}}var creds=sourceCredentials(p);if(creds)payload.credentials=creds;note('Saving source configuration...','info');try{var result=await admin('/api/v1/admin/sources',{method:'POST',body:JSON.stringify(payload)}),source=result.source;if(!source||!source.id)throw new Error('SOURCE_CREATE_FAILED');var oneTime=result.oneTimeSigningSecret||result.signingSecret||null;if(p==='external_mtproto'){var rotated=await admin('/api/v1/admin/sources/'+encodeURIComponent(source.id)+'/ingress-secret',{method:'POST',body:'{}'});oneTime=rotated.oneTimeSigningSecret;showExternalSetup(source,oneTime,payload)}else if(oneTime){showExternalSetup(source,oneTime,payload)}note('Source saved. Use Connect below to activate it.','success');await refreshSourceControls()}catch(e){note('Source failed: '+String(e.message||e),'error')}}
function showExternalSetup(source,secret,payload){var box=q('externalSourceSetup');if(!box||!secret)return;var endpoint=location.origin+'/api/v1/events',chats=(payload.config&&payload.config.allowed_chat_ids||[]).join(',');box.innerHTML='<div class="notice success"><b>Copy this setup now — the signing secret is shown once.</b></div><pre class="code">TRADING_ENDPOINT='+safe(endpoint)+'\\nTRADING_SOURCE_ID='+safe(source.id)+'\\nTRADING_SOURCE_SECRET='+safe(secret)+(payload.externalIdentity?'\\nTELEGRAM_ACCOUNT_SCOPE='+safe(payload.externalIdentity):'')+(chats?'\\nALLOWED_CHAT_IDS='+safe(chats):'')+'</pre><div class="muted small">Your userbot must POST signed event JSON to /api/v1/events with X-Mkety-Source-Id, X-Mkety-Timestamp and X-Mkety-Signature. Adding only the endpoint URL is not sufficient.</div>'}
async function toggleSource(id,enabled){try{await admin('/api/v1/admin/sources/'+encodeURIComponent(id)+'/'+(enabled?'enable':'disable'),{method:'POST',body:'{}'});note(enabled?'Source connected.':'Source disconnected.','success');await refreshSourceControls()}catch(e){note((enabled?'Connect':'Disconnect')+' failed: '+String(e.message||e),'error')}}
async function refreshSourceControls(){var rows=q('enterpriseSourceControlRows');if(!rows)return;try{var r=await admin('/api/v1/admin/sources'),items=r.sources||[];rows.innerHTML=items.length?items.map(function(x){return '<div class="toolbar" style="border-top:1px solid #e8edf4;padding:8px 0"><div><b>'+safe(x.displayName||x.sourceInstanceId)+'</b><div class="muted small">'+safe(x.providerType)+' • '+safe(x.enabled?'Connected':'Disconnected')+'</div></div><button class="btn '+(x.enabled?'secondary':'primary')+'" data-source-toggle="'+safe(x.id)+'" data-source-enable="'+(x.enabled?'0':'1')+'">'+(x.enabled?'Disconnect':'Connect')+'</button></div>'}).join(''):'<div class="empty">No sources yet.</div>'}catch(e){rows.innerHTML='<div class="notice error">Unable to load source connection state: '+safe(e.message||e)+'</div>'}}
var AI={openai:{models:['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],base:'https://api.openai.com/v1'},gemini:{models:['gemini-3.8-flash'],base:''},deepseek:{models:['deepseek-v4-flash','deepseek-v4-pro'],base:'https://api.deepseek.com'},groq:{models:['openai/gpt-oss-120b','openai/gpt-oss-20b'],base:'https://api.groq.com/openai/v1'},cloudflare_ai:{models:['@cf/openai/gpt-oss-120b','@cf/deepseek-ai/deepseek-v4-flash-0731','@cf/zai-org/glm-5.3-flash'],base:''},custom:{models:[],base:''}};
function configureAI(){var provider=q('aiProvider'),model=q('aiModel'),base=q('aiBaseUrl');if(!provider||!model||!base)return;var cfg=AI[provider.value]||AI.custom;var list=q('currentAiModels');if(!list){list=document.createElement('datalist');list.id='currentAiModels';document.body.appendChild(list);model.setAttribute('list','currentAiModels')}list.innerHTML=cfg.models.map(function(x){return '<option value="'+safe(x)+'"></option>'}).join('');model.placeholder=cfg.models[0]||'Provider model ID';if(!model.value||model.dataset.autoModel==='1'){model.value=cfg.models[0]||'';model.dataset.autoModel='1'}if(provider.value!=='custom'){base.value=cfg.base;base.readOnly=true}else{base.readOnly=false;if(base.dataset.autoBase==='1')base.value=''}base.dataset.autoBase='1'}
function init(){ensureSourceExtras();renderSourceExtras();var provider=q('sourceProvider');if(provider)provider.addEventListener('change',function(){setTimeout(renderSourceExtras,0)});var create=q('createSourceBtn');if(create){create.textContent='Save source';create.addEventListener('click',createSourceComplete,true)}document.addEventListener('click',function(ev){var t=ev.target&&ev.target.closest&&ev.target.closest('[data-source-toggle]');if(!t)return;ev.preventDefault();toggleSource(t.dataset.sourceToggle,t.dataset.sourceEnable==='1')});var ai=q('aiProvider');if(ai){ai.addEventListener('change',function(){var m=q('aiModel');if(m){m.value='';m.dataset.autoModel='1'}configureAI()});configureAI()}setTimeout(refreshSourceControls,350);setTimeout(refreshSourceControls,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();</script>`;
  return String(html).replace('</body>', script + '</body>');
}
