export function renderDashboard(env = {}) {
  const runtime = {
    tradingAccessEnabled: String(env.TRADING_ACCESS_ENABLED ?? '').toLowerCase() === 'true',
    brokerExecutionEnabled: String(env.BROKER_EXECUTION_ENABLED ?? '').toLowerCase() === 'true',
    customHostnamesEnabled: String(env.TRADING_CUSTOM_HOSTNAMES_ENABLED ?? '').toLowerCase() === 'true',
    executionTransportMode: String(env.TRADING_EXECUTION_TRANSPORT_MODE ?? 'real').toLowerCase() === 'simulation' ? 'simulation' : 'real',
  };

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mkety Trading V1</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui;color:#142033;background:#f6f8fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1240px;margin:auto;padding:24px}.top,.toolbar,.row{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.brand h1{margin:0}.muted{color:#64748b;font-size:12px}.card{background:#fff;border:1px solid #dfe5ee;border-radius:14px;box-shadow:0 3px 16px rgba(15,23,42,.05)}.auth{padding:16px;display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end}.field label,.auth label{display:block;font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;margin-bottom:6px}.field input,.field select,.field textarea,.auth input{width:100%;padding:10px;border:1px solid #cfd8e6;border-radius:9px}.btn{border:0;border-radius:9px;padding:9px 12px;font-weight:700;cursor:pointer}.primary{background:#0f172a;color:white}.secondary{background:#eef2f7;color:#1e293b}.good{background:#ecfdf5;color:#047857}.warn{background:#fff7ed;color:#9a3412}.danger{background:#fef2f2;color:#b91c1c}.tabs{display:flex;gap:7px;padding:8px;margin:16px 0;overflow:auto}.tab{border:0;background:transparent;padding:9px 12px;border-radius:8px;font-weight:700;color:#64748b;white-space:nowrap}.tab.active{background:#0f172a;color:#fff}.panel{padding:18px}.notice{padding:12px 14px;border-radius:10px;margin:12px 0;font-size:13px}.notice.info{background:#eff6ff;color:#1e40af}.notice.ok{background:#ecfdf5;color:#065f46}.notice.error{background:#fef2f2;color:#991b1b}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.stat{padding:15px}.stat b{font-size:25px;display:block}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{padding:10px;border-bottom:1px solid #e8edf4;text-align:left;vertical-align:top}.table th{font-size:11px;text-transform:uppercase;color:#64748b;background:#f8fafc}.badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef2f7;font-size:11px;font-weight:700}.actions{display:flex;gap:6px;flex-wrap:wrap}.form{display:none;padding:16px;margin:12px 0}.form.open{display:block}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.full{grid-column:1/-1}.empty{text-align:center;padding:26px;color:#64748b}.json{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;padding:14px;border-radius:10px;overflow:auto;max-height:430px;font:12px ui-monospace,monospace}.hidden{display:none!important}@media(max-width:760px){.shell{padding:12px}.auth,.grid,.form-grid{grid-template-columns:1fr}}
</style>
</head>
<body><div class="shell">
<div class="top"><div class="brand"><h1>Mkety Trading V1</h1><div class="muted">Production API control surface • workspace-scoped • fail-closed</div></div><div id="runtime" class="muted"></div></div>
<div class="card auth"><div><label>Workspace ID</label><input id="workspaceId" placeholder="Trading workspace UUID"></div><div><label>Mkety Trading Bearer</label><input id="bearer" type="password" placeholder="Short-lived signed Mkety assertion"></div><button id="connectBtn" class="btn primary">Connect</button></div>
<div id="message"></div>
<div id="tabs" class="card tabs"><button class="tab active" data-tab="overview">Overview</button><button class="tab" data-tab="sources">Sources</button><button class="tab" data-tab="accounts">Accounts & Risk</button><button class="tab" data-tab="members">Users</button><button class="tab" data-tab="operations">Operations</button><button class="tab" data-tab="hostnames">Domains</button><button class="tab" data-tab="settings">Settings</button></div>
<div class="card panel"><section id="view-overview"></section><section id="view-sources" class="hidden"></section><section id="view-accounts" class="hidden"></section><section id="view-members" class="hidden"></section><section id="view-operations" class="hidden"></section><section id="view-hostnames" class="hidden"></section><section id="view-settings" class="hidden"></section></div>
</div>
<script>
(function(){
'use strict';
var runtime=${JSON.stringify(runtime)};
var state={workspace:null,members:[],sources:[],accounts:[],hostnames:[],operations:null,masterBrokerExecutionEnabled:false,activeTab:'overview'};
var SOURCE_PROVIDERS={
 cloudflare_container_mtproto:{family:'telegram',type:'telegram_mtproto',credential:'mtproto'},
 cloudflare_do_mtproto:{family:'telegram',type:'telegram_mtproto',credential:'mtproto'},
 external_mtproto:{family:'telegram',type:'telegram_mtproto',credential:'mtproto'},
 tradingview_webhook:{family:'tradingview',type:'tradingview_webhook',credential:null},
 custom_signed_api:{family:'custom_api',type:'custom_signed_api',credential:null},
 mt5_source_bridge:{family:'mt5',type:'mt5_source_bridge',credential:'mt5'},
 ctrader_source:{family:'ctrader',type:'ctrader_source',credential:'ctrader'}
};
var workspaceInput=document.getElementById('workspaceId'),bearerInput=document.getElementById('bearer');
workspaceInput.value=localStorage.getItem('mketyTradingWorkspaceId')||'';bearerInput.value=sessionStorage.getItem('mketyTradingBearer')||'';
document.getElementById('runtime').textContent='Access '+(runtime.tradingAccessEnabled?'ON':'OFF')+' • Broker '+(runtime.brokerExecutionEnabled?'ON':'OFF')+' • Transport '+runtime.executionTransportMode.toUpperCase()+' • Domains '+(runtime.customHostnamesEnabled?'ON':'OFF');
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function msg(t,k){document.getElementById('message').innerHTML=t?'<div class="notice '+(k||'info')+'">'+esc(t)+'</div>':''}
function cfg(){return{workspaceId:workspaceInput.value.trim(),bearer:bearerInput.value.trim()}}
async function v1(path,options){options=options||{};var c=cfg();if(!c.workspaceId)throw new Error('Workspace ID is required');if(!c.bearer)throw new Error('Mkety Trading bearer is required');var headers=Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':c.workspaceId,'Authorization':'Bearer '+c.bearer},options.headers||{});var r=await fetch(path,Object.assign({},options,{headers:headers}));var body;try{body=await r.json()}catch(_){body={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||!body||body.ok===false)throw new Error((body&&(body.reason||body.error))||('HTTP_'+r.status));return body}
function persist(){var c=cfg();localStorage.setItem('mketyTradingWorkspaceId',c.workspaceId);sessionStorage.setItem('mketyTradingBearer',c.bearer)}
async function refreshWorkspace(){state.workspace=(await v1('/api/v1/admin/workspace')).workspace}
async function refreshMembers(){state.members=(await v1('/api/v1/admin/members')).members||[]}
async function refreshSources(){state.sources=(await v1('/api/v1/admin/sources')).sources||[]}
async function refreshAccounts(){var r=await v1('/api/v1/admin/accounts');state.accounts=r.accounts||[];state.masterBrokerExecutionEnabled=!!r.masterBrokerExecutionEnabled}
async function refreshHostnames(){state.hostnames=(await v1('/api/v1/admin/hostnames')).hostnames||[]}
async function refreshOperations(){state.operations=await v1('/api/v1/admin/operations')}
async function connect(){persist();msg('Loading Trading workspace...','info');try{await Promise.all([refreshWorkspace(),refreshMembers(),refreshSources(),refreshAccounts(),refreshHostnames()]);try{await refreshOperations()}catch(e){state.operations={ok:false,reason:e.message}}msg('Connected to canonical Trading V1 API.','ok');renderAll()}catch(e){msg('Connection failed: '+e.message,'error');renderAll()}}
function overview(){if(!state.workspace)return '<div class="empty">Enter a workspace ID and Mkety bearer, then Connect.</div>';var w=state.workspace;return '<div class="toolbar"><div><h2>'+esc(w.name||'Trading workspace')+'</h2><div class="muted">'+esc(w.id)+' • '+esc(w.owner_email||'')+'</div></div><span class="badge">Trading access '+(w.trading_access_enabled?'enabled':'disabled')+'</span></div><div class="grid"><div class="card stat">Sources<b>'+state.sources.length+'</b></div><div class="card stat">Accounts<b>'+state.accounts.length+'</b></div><div class="card stat">Users<b>'+state.members.length+'</b></div></div><div class="notice info">Every mutation reloads canonical V1 server state. No direct Supabase table proxy is used.</div>'}
function sourceRows(){if(!state.sources.length)return '<tr><td colspan="8" class="empty">No sources configured.</td></tr>';return state.sources.map(function(s){var credentialButton=s.providerType==='tradingview_webhook'?'':'<button class="btn secondary" data-action="source-credentials" data-id="'+esc(s.id)+'" data-provider="'+esc(s.providerType)+'">'+(s.providerType==='custom_signed_api'?'Rotate signing secret':'Replace credentials')+'</button>';return '<tr><td>'+esc(s.displayName||s.sourceInstanceId||s.id)+'</td><td>'+esc(s.providerType)+'</td><td>'+esc(s.sourceFamily)+'</td><td><span class="badge">'+(s.enabled?'Enabled':'Disabled')+'</span></td><td>'+esc((s.health&&s.health.status)||'—')+'</td><td>'+esc(s.credentialConfigured?'Configured':'Not configured')+'</td><td>'+esc(s.isDefault?'Default':'—')+'</td><td class="actions"><button class="btn '+(s.enabled?'warn':'good')+'" data-action="source-state" data-id="'+esc(s.id)+'" data-enabled="'+(!s.enabled)+'">'+(s.enabled?'Disable':'Enable')+'</button><button class="btn secondary" data-action="source-default" data-id="'+esc(s.id)+'" data-family="'+esc(s.sourceFamily)+'">Set default</button>'+credentialButton+'</td></tr>'}).join('')}
function sourceCredentialHelp(){return '<div id="sourceCredentialHelp" class="notice info">MTProto: apiId, apiHash, session. MT5: bridgeUrl, bridgeSecret. cTrader: clientId, clientSecret, accessToken, optional refreshToken. TradingView/custom signed API: no credentials.</div>'}
function sourcesView(){return '<div class="toolbar"><div><h2>Sources</h2><div class="muted">Provider family/type is server-contract owned. Disable is the audit-safe removal lifecycle.</div></div><button class="btn primary" data-toggle="source-form">Add source</button></div><div id="source-form" class="card form"><div class="form-grid"><div class="field"><label>Provider</label><select id="sourceProvider"><option>cloudflare_container_mtproto</option><option>cloudflare_do_mtproto</option><option>external_mtproto</option><option>tradingview_webhook</option><option>custom_signed_api</option><option>mt5_source_bridge</option><option>ctrader_source</option></select></div><div class="field"><label>Source instance ID</label><input id="sourceInstance"></div><div class="field"><label>Display name</label><input id="sourceName"></div><div class="field"><label>Priority</label><input id="sourcePriority" type="number" value="0"></div><div class="field full"><label>Credentials JSON</label><textarea id="sourceCredentials" rows="5"></textarea></div><div class="full">'+sourceCredentialHelp()+'<button class="btn primary" data-action="create-source">Create disabled source</button></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Provider</th><th>Family</th><th>State</th><th>Health</th><th>Credentials</th><th>Default</th><th>Actions</th></tr></thead><tbody>'+sourceRows()+'</tbody></table></div>'}
function accountRows(){if(!state.accounts.length)return '<tr><td colspan="8" class="empty">No broker accounts configured.</td></tr>';return state.accounts.map(function(a){return '<tr><td>'+esc(a.label||a.id)+'</td><td>'+esc(a.platform)+'</td><td>'+esc(a.accountId)+'</td><td>'+esc(a.serverName||'—')+'</td><td>'+esc(a.active?'Active':'Inactive')+'</td><td>'+esc(a.executionEnabled?'ON':'OFF')+'</td><td>'+esc(a.killSwitch?'ON':'OFF')+'</td><td class="actions"><button class="btn secondary" data-action="account-active" data-id="'+esc(a.id)+'" data-enabled="'+(!a.active)+'">'+(a.active?'Deactivate':'Activate')+'</button><button class="btn '+(a.executionEnabled?'warn':'good')+'" data-action="account-execution" data-id="'+esc(a.id)+'" data-enabled="'+(!a.executionEnabled)+'">'+(a.executionEnabled?'Disable exec':'Enable exec')+'</button><button class="btn '+(a.killSwitch?'good':'danger')+'" data-action="account-kill" data-id="'+esc(a.id)+'" data-enabled="'+(!a.killSwitch)+'">'+(a.killSwitch?'Release kill':'Engage kill')+'</button><button class="btn secondary" data-action="account-credentials" data-id="'+esc(a.id)+'">Replace credentials</button></td></tr>'}).join('')}
function accountsView(){return '<div class="toolbar"><div><h2>Broker accounts & risk</h2><div class="muted">MT5/cTrader only. Deactivation is the audit-safe removal lifecycle; credentials can be rotated without exposing stored secrets.</div></div><button class="btn primary" data-toggle="account-form">Add account</button></div><div class="notice info">Master broker execution fuse: '+(state.masterBrokerExecutionEnabled?'ENABLED':'DISABLED')+'</div><div id="account-form" class="card form"><div class="form-grid"><div class="field"><label>Label</label><input id="accountLabel"></div><div class="field"><label>Platform</label><select id="accountPlatform"><option value="mt5">MT5</option><option value="ctrader">cTrader</option></select></div><div class="field"><label>Account ID</label><input id="accountExternalId"></div><div class="field"><label>Server name</label><input id="accountServer"></div><div class="field"><label>Lot sizing</label><select id="lotSizing"><option value="fixed">fixed</option></select></div><div class="field"><label>Lot value</label><input id="lotValue" type="number" step="0.01" value="0.01"></div><div class="field full"><label>Credentials JSON</label><textarea id="accountCredentials" rows="5"></textarea></div><div class="full"><div class="notice info">MT5 credentials: bridgeUrl, bridgeSecret. cTrader: clientId, clientSecret, accessToken, optional refreshToken.</div><button class="btn primary" data-action="create-account">Create safe inactive account</button></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Label</th><th>Platform</th><th>Account</th><th>Server</th><th>Active</th><th>Execution</th><th>Kill</th><th>Actions</th></tr></thead><tbody>'+accountRows()+'</tbody></table></div>'}
function memberRows(){if(!state.members.length)return '<tr><td colspan="4" class="empty">No Trading members.</td></tr>';return state.members.map(function(m){return '<tr><td>'+esc(m.subject)+'</td><td>'+esc(m.role)+'</td><td>'+esc(m.enabled?'Enabled':'Disabled')+'</td><td class="actions"><button class="btn secondary" data-action="member-state" data-subject="'+encodeURIComponent(m.subject)+'" data-enabled="'+(!m.enabled)+'">'+(m.enabled?'Disable':'Enable')+'</button><button class="btn secondary" data-action="member-role" data-subject="'+encodeURIComponent(m.subject)+'">Change role</button></td></tr>'}).join('')}
function membersView(){return '<div class="toolbar"><div><h2>Users</h2><div class="muted">Supabase membership is final Trading authorization/revocation authority. Disabling removes Trading access while preserving audit history.</div></div><button class="btn primary" data-toggle="member-form">Add member</button></div><div id="member-form" class="card form"><div class="form-grid"><div class="field"><label>Mkety subject</label><input id="memberSubject"></div><div class="field"><label>Role</label><select id="memberRole"><option>owner</option><option>admin</option><option>operator</option><option>viewer</option></select></div><div class="full"><button class="btn primary" data-action="create-member">Add / update member</button></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Subject</th><th>Role</th><th>State</th><th>Actions</th></tr></thead><tbody>'+memberRows()+'</tbody></table></div>'}
function operationsView(){return '<div class="toolbar"><div><h2>Operations & audit</h2><div class="muted">Canonical operational state from V1.</div></div><div class="actions"><button class="btn secondary" data-action="refresh-operations">Refresh</button><button class="btn primary" data-action="audit-event">Audit event ID</button></div></div><pre class="json">'+esc(JSON.stringify(state.operations||{message:'No operations data loaded.'},null,2))+'</pre><div id="eventAudit"></div>'}
function hostnameRows(){if(!state.hostnames.length)return '<tr><td colspan="4" class="empty">No custom domains.</td></tr>';return state.hostnames.map(function(h){return '<tr><td>'+esc(h.hostname)+'</td><td>'+esc(h.status)+'</td><td>'+esc(h.verifiedAt||'—')+'</td><td><button class="btn secondary" data-action="verify-hostname" data-id="'+esc(h.id)+'">Verify</button></td></tr>'}).join('')}
function hostnamesView(){return '<div class="toolbar"><div><h2>Domains</h2><div class="muted">Routing context only; never workspace authority.</div></div><button class="btn primary" data-toggle="hostname-form">Add hostname</button></div><div id="hostname-form" class="card form"><div class="form-grid"><div class="field"><label>Hostname</label><input id="hostnameValue"></div><div class="field"><label>&nbsp;</label><button class="btn primary" data-action="create-hostname">Create</button></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Hostname</th><th>Status</th><th>Verified</th><th>Action</th></tr></thead><tbody>'+hostnameRows()+'</tbody></table></div>'}
function settingsView(){return '<div class="toolbar"><div><h2>Settings</h2><div class="muted">Deployment-owned security/runtime settings are intentionally read-only.</div></div></div><div class="grid"><div class="card stat">Trading access<b>'+(runtime.tradingAccessEnabled?'ON':'OFF')+'</b></div><div class="card stat">Broker fuse<b>'+(runtime.brokerExecutionEnabled?'ON':'OFF')+'</b></div><div class="card stat">Transport<b>'+esc(runtime.executionTransportMode.toUpperCase())+'</b></div></div><div class="notice info">Mkety issuer/audience/JWKS, encryption keys and provider secrets are not editable from the browser. Browser callers cannot select simulation transport.</div>'}
function renderAll(){document.getElementById('view-overview').innerHTML=overview();document.getElementById('view-sources').innerHTML=sourcesView();document.getElementById('view-accounts').innerHTML=accountsView();document.getElementById('view-members').innerHTML=membersView();document.getElementById('view-operations').innerHTML=operationsView();document.getElementById('view-hostnames').innerHTML=hostnamesView();document.getElementById('view-settings').innerHTML=settingsView()}
async function mutate(fn,success){msg('Applying change...','info');try{await fn();msg(success||'Saved.','ok');renderAll()}catch(e){msg('Action failed: '+e.message,'error');renderAll()}}
function readJson(id){var raw=document.getElementById(id).value.trim();if(!raw)return {};try{return JSON.parse(raw)}catch(_){throw new Error('Invalid JSON in '+id)}}
function promptJson(label){var raw=prompt(label);if(raw==null)return null;try{return JSON.parse(raw)}catch(_){throw new Error('Invalid credentials JSON')}}
document.getElementById('connectBtn').addEventListener('click',connect);
document.getElementById('tabs').addEventListener('click',function(e){var t=e.target.closest('[data-tab]');if(!t)return;state.activeTab=t.dataset.tab;document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x.dataset.tab===state.activeTab)});document.querySelectorAll('section[id^="view-"]').forEach(function(x){x.classList.toggle('hidden',x.id!=='view-'+state.activeTab)})});
document.body.addEventListener('click',function(e){var toggle=e.target.closest('[data-toggle]');if(toggle){var form=document.getElementById(toggle.dataset.toggle);if(form)form.classList.toggle('open');return}var b=e.target.closest('[data-action]');if(!b)return;var action=b.dataset.action;
 if(action==='create-member')return mutate(async function(){await v1('/api/v1/admin/members',{method:'POST',body:JSON.stringify({subject:document.getElementById('memberSubject').value.trim(),role:document.getElementById('memberRole').value})});await refreshMembers()},'Member saved.');
 if(action==='member-state')return mutate(async function(){await v1('/api/v1/admin/members/'+b.dataset.subject+'/'+(b.dataset.enabled==='true'?'enable':'disable'),{method:'POST',body:'{}'});await refreshMembers()},'Member state updated.');
 if(action==='member-role'){var role=prompt('New role: owner, admin, operator, viewer');if(!role)return;return mutate(async function(){await v1('/api/v1/admin/members/'+b.dataset.subject+'/role',{method:'POST',body:JSON.stringify({role:role})});await refreshMembers()},'Member role updated.')}
 if(action==='create-source')return mutate(async function(){var provider=document.getElementById('sourceProvider').value,def=SOURCE_PROVIDERS[provider];if(!def)throw new Error('Unsupported source provider');var payload={providerType:provider,sourceFamily:def.family,sourceType:def.type,sourceInstanceId:document.getElementById('sourceInstance').value.trim(),displayName:document.getElementById('sourceName').value.trim(),priority:Number(document.getElementById('sourcePriority').value||0)};var raw=document.getElementById('sourceCredentials').value.trim();if(def.credential){if(!raw)throw new Error('Credentials are required for '+provider);payload.credentials=JSON.parse(raw)}else if(raw){throw new Error('This provider does not accept credentials')}var created=await v1('/api/v1/admin/sources',{method:'POST',body:JSON.stringify(payload)});if(created.oneTimeSigningSecret)alert('Copy this one-time signing secret now: '+created.oneTimeSigningSecret);await refreshSources()},'Source created disabled.');
 if(action==='source-state')return mutate(async function(){await v1('/api/v1/admin/sources/'+encodeURIComponent(b.dataset.id)+'/'+(b.dataset.enabled==='true'?'enable':'disable'),{method:'POST',body:'{}'});await refreshSources()},'Source state updated.');
 if(action==='source-default')return mutate(async function(){await v1('/api/v1/admin/sources/'+encodeURIComponent(b.dataset.id)+'/default',{method:'POST',body:JSON.stringify({sourceFamily:b.dataset.family})});await refreshSources()},'Default source updated.');
 if(action==='source-credentials')return mutate(async function(){var provider=b.dataset.provider;var body={};if(provider!=='custom_signed_api'){var credentials=promptJson('Paste replacement credentials JSON');if(credentials==null)return;body={credentials:credentials}}var replaced=await v1('/api/v1/admin/sources/'+encodeURIComponent(b.dataset.id)+'/credentials',{method:'PUT',body:JSON.stringify(body)});if(replaced.oneTimeSigningSecret)alert('Copy this new one-time signing secret now: '+replaced.oneTimeSigningSecret);await refreshSources()},'Source credentials rotated.');
 if(action==='create-account')return mutate(async function(){await v1('/api/v1/admin/accounts',{method:'POST',body:JSON.stringify({label:document.getElementById('accountLabel').value.trim(),platform:document.getElementById('accountPlatform').value,accountId:document.getElementById('accountExternalId').value.trim(),serverName:document.getElementById('accountServer').value.trim(),lotSizingType:document.getElementById('lotSizing').value,lotValue:Number(document.getElementById('lotValue').value),credentials:readJson('accountCredentials')})});await refreshAccounts()},'Account created inactive with kill switch engaged.');
 if(action==='account-active')return mutate(async function(){await v1('/api/v1/admin/accounts/'+encodeURIComponent(b.dataset.id)+'/active',{method:'POST',body:JSON.stringify({enabled:b.dataset.enabled==='true'})});await refreshAccounts()},'Account activation updated.');
 if(action==='account-execution')return mutate(async function(){await v1('/api/v1/admin/accounts/'+encodeURIComponent(b.dataset.id)+'/execution',{method:'POST',body:JSON.stringify({enabled:b.dataset.enabled==='true'})});await refreshAccounts()},'Execution flag updated.');
 if(action==='account-kill')return mutate(async function(){await v1('/api/v1/admin/accounts/'+encodeURIComponent(b.dataset.id)+'/kill-switch',{method:'POST',body:JSON.stringify({enabled:b.dataset.enabled==='true'})});await refreshAccounts()},'Kill switch updated.');
 if(action==='account-credentials')return mutate(async function(){var credentials=promptJson('Paste replacement broker credentials JSON');if(credentials==null)return;await v1('/api/v1/admin/accounts/'+encodeURIComponent(b.dataset.id)+'/credentials',{method:'PUT',body:JSON.stringify({credentials:credentials})});await refreshAccounts()},'Broker credentials rotated.');
 if(action==='create-hostname')return mutate(async function(){await v1('/api/v1/admin/hostnames',{method:'POST',body:JSON.stringify({hostname:document.getElementById('hostnameValue').value.trim()})});await refreshHostnames()},'Hostname created.');
 if(action==='verify-hostname')return mutate(async function(){await v1('/api/v1/admin/hostnames/'+encodeURIComponent(b.dataset.id)+'/verify',{method:'POST',body:'{}'});await refreshHostnames()},'Hostname verification refreshed.');
 if(action==='refresh-operations')return mutate(refreshOperations,'Operations refreshed.');
 if(action==='audit-event'){var id=prompt('Canonical event ID');if(!id)return;return mutate(async function(){var data=await v1('/api/v1/admin/events/'+encodeURIComponent(id)+'/audit');document.getElementById('eventAudit').innerHTML='<pre class="json">'+esc(JSON.stringify(data,null,2))+'</pre>'},'Event audit loaded.')}
});
renderAll();if(workspaceInput.value&&bearerInput.value)connect();
})();
</script></body></html>`;
}
