export function withEnterpriseLiveExecutionControls(html) {
  const script = `<script>(function(){
function q(id){return document.getElementById(id)}
function safe(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function auth(){return {workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function api(path,options){options=options||{};var s=auth();if(!s.workspace||!s.bearer)throw new Error('SESSION_REQUIRED');var r=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':s.workspace,'Authorization':'Bearer '+s.bearer},options.headers||{})}));var b={};try{b=await r.json()}catch(_){}if(!r.ok||b.ok===false)throw new Error(b.reason||('HTTP_'+r.status));return b}
function note(t,type){var e=q('workspaceMessage');if(!e)return;e.className='notice '+(type||'info');e.textContent=t}
function ensurePanel(){var rows=q('enterpriseAccountControlRows')||q('accountRows');if(!rows||q('enterpriseLiveExecutionControls'))return null;var card=rows.closest('.card');if(!card)return null;var box=document.createElement('div');box.id='enterpriseLiveExecutionControls';box.className='formbox';box.innerHTML='<b>Live / Real-Money Controls</b><div class="notice info small">DEMO accounts never need this switch. For LIVE accounts, real-money execution still requires Global Live / Real-Money ON, normal Execution ON, Active ON, Kill Switch OFF, and every route/risk/symbol gate.</div><div id="enterpriseLiveExecutionRows"></div>';card.appendChild(box);return box}
function button(account){if(String(account.environment||'').toLowerCase()!=='live')return '<button class="btn secondary" disabled>Demo — live switch not applicable</button>';return '<button class="btn '+(account.liveExecutionEnabled?'danger':'good')+'" data-account-live="'+safe(account.id)+'" data-enable="'+(account.liveExecutionEnabled?'0':'1')+'">'+(account.liveExecutionEnabled?'Disable Live / Real-Money':'Enable Live / Real-Money')+'</button>'}
async function refresh(){ensurePanel();var target=q('enterpriseLiveExecutionRows');if(!target)return;try{var body=await api('/api/v1/admin/accounts');var accounts=body.accounts||[];target.innerHTML=accounts.length?accounts.map(function(a){var env=String(a.environment||'unverified').toUpperCase();return '<div class="formbox"><div class="toolbar"><div><b>'+safe(a.label||a.accountId)+'</b> <span class="pill">'+safe(a.platform||'broker')+'</span> <span class="pill">'+safe(env)+'</span><div class="muted small">Normal execution: '+(a.executionEnabled?'ON':'OFF')+' • Live permission: '+(a.liveExecutionEnabled?'ON':'OFF')+' • '+(a.killSwitch?'Kill switch ON':'Kill switch OFF')+'</div></div><div class="actions">'+button(a)+'</div></div></div>'}).join(''):'<div class="empty">No broker connections yet.</div>'}catch(e){if(String(e.message)!=='SESSION_REQUIRED')target.innerHTML='<div class="notice error">Unable to load live controls: '+safe(e.message)+'</div>'}}
async function toggle(id,next){if(next&&!confirm('Enable LIVE / REAL-MONEY execution for this LIVE broker account? Only continue after demo acceptance has passed.'))return;try{await api('/api/v1/admin/accounts/'+encodeURIComponent(id)+'/live-execution',{method:'POST',body:JSON.stringify({enabled:next})});note(next?'Live / Real-Money permission enabled for this account.':'Live / Real-Money permission disabled for this account.','success');await refresh()}catch(e){note('Live execution update failed: '+String(e.message||e),'error')}}
document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest&&ev.target.closest('[data-account-live]');if(!b)return;ev.preventDefault();toggle(b.dataset.accountLive,b.dataset.enable==='1')});
var observer=new MutationObserver(function(){if(q('workspaceShell')&&!q('workspaceShell').classList.contains('hidden'))refresh()});observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
document.addEventListener('visibilitychange',function(){if(!document.hidden)refresh()});setInterval(function(){if(q('workspaceShell')&&!q('workspaceShell').classList.contains('hidden'))refresh()},10000);setTimeout(refresh,500);
})();</script>`;
  return String(html).replace('</body>', script + '</body>');
}
