function enabled(value) {
  return ['1', 'true', 'yes', 'on'].includes(String(value ?? '').trim().toLowerCase());
}

function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[char]));
}

export function renderTradingLaunchConsole(env = {}) {
  const broker = enabled(env.BROKER_EXECUTION_ENABLED);
  const tradingAccess = enabled(env.TRADING_ACCESS_ENABLED);
  const customDomains = enabled(env.TRADING_CUSTOM_HOSTNAMES_ENABLED);
  const runtime = { broker, tradingAccess, customDomains };
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mkety Trading Launch Console</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui;color:#102033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1240px;margin:auto;padding:24px}.hero{background:#0f172a;color:#fff;border-radius:18px;padding:24px;margin-bottom:16px}.hero h1{margin:0 0 7px}.muted{color:#64748b}.hero .muted{color:#cbd5e1}.pill{display:inline-block;border-radius:999px;padding:5px 9px;background:#eef2ff;margin:4px 4px 0 0;font-size:12px;font-weight:700}.danger{background:#fee2e2;color:#991b1b}.ok{background:#dcfce7;color:#166534}.card{background:#fff;border:1px solid #dbe3ef;border-radius:14px;padding:18px;box-shadow:0 3px 14px rgba(15,23,42,.05);margin-bottom:14px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid .card{margin:0}.auth,.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.full{grid-column:1/-1}.field label{display:block;font-size:11px;font-weight:800;color:#64748b;text-transform:uppercase;margin-bottom:5px}.field input,.field select,.field textarea{width:100%;padding:10px;border:1px solid #cfd8e6;border-radius:9px;background:#fff}.btn{border:0;border-radius:9px;padding:9px 12px;font-weight:750;cursor:pointer}.primary{background:#0f172a;color:#fff}.secondary{background:#eef2f7;color:#1e293b}.warn{background:#fff7ed;color:#9a3412}.good{background:#ecfdf5;color:#047857}.notice{padding:11px 13px;border-radius:10px;margin:10px 0;font-size:13px}.info{background:#eff6ff;color:#1e40af}.error{background:#fef2f2;color:#991b1b}.success{background:#ecfdf5;color:#065f46}.toolbar,.actions{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap}.actions{justify-content:flex-start}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{padding:9px;border-bottom:1px solid #e8edf4;text-align:left;vertical-align:top}.table th{font-size:11px;text-transform:uppercase;color:#64748b;background:#f8fafc}.badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef2f7;font-size:11px;font-weight:700}.small{font-size:13px;line-height:1.55}.code{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;border-radius:9px;padding:11px;font:12px ui-monospace,monospace;overflow:auto}.form{display:none;margin-top:12px}.form.open{display:block}.empty{padding:18px;text-align:center;color:#64748b}.section-title{margin:0 0 4px}.links a{margin-right:12px}.tabs{display:flex;gap:7px;overflow:auto;margin:14px 0}.tab{border:0;background:#e9eef6;padding:9px 12px;border-radius:9px;font-weight:750;white-space:nowrap}.tab.active{background:#0f172a;color:#fff}.view{display:none}.view.active{display:block}@media(max-width:760px){.shell{padding:12px}.grid,.auth,.form-grid{grid-template-columns:1fr}.full{grid-column:auto}}
</style></head><body><main class="shell">
<div class="hero"><h1>Mkety Trading Launch Console</h1><p class="muted">Enterprise setup for sources, destinations, formatting, routing, MTProto, domains, risk visibility, and safe end-to-end testing.</p><div><span class="pill ${tradingAccess ? 'ok' : 'danger'}">TRADING_ACCESS_ENABLED=${tradingAccess}</span><span class="pill ${broker ? 'danger' : 'ok'}">BROKER_EXECUTION_ENABLED=${broker}</span><span class="pill ${customDomains ? 'ok' : ''}">TRADING_CUSTOM_HOSTNAMES_ENABLED=${customDomains}</span></div></div>
<section class="card"><div class="toolbar"><div><h2 class="section-title">Enterprise Owner Workspace</h2><div class="muted">Connect with the short-lived Trading bearer for this exact workspace.</div></div><a href="/">Back to workspace dashboard</a></div><div class="auth"><div class="field"><label>Workspace ID</label><input id="workspaceId" autocomplete="off" placeholder="Workspace UUID"></div><div class="field"><label>Trading bearer</label><input id="bearer" type="password" autocomplete="off" placeholder="Short-lived bearer"></div><div class="full"><button id="connectBtn" class="btn primary">Connect launch console</button></div></div><div id="message"></div></section>
<div class="tabs"><button class="tab active" data-tab="destinations">Destinations</button><button class="tab" data-tab="templates">Formatting</button><button class="tab" data-tab="routes">Routes</button><button class="tab" data-tab="mtproto">MTProto</button><button class="tab" data-tab="risk">Risk & Audit</button></div>
<section id="view-destinations" class="view active"><div class="card"><div class="toolbar"><div><h2 class="section-title">Destinations</h2><div class="muted">Telegram, signed internal webhook, audit-only, and broker target records.</div></div><button class="btn primary" data-toggle="destination-form">Add destination</button></div><div id="destination-form" class="form"><div class="form-grid"><div class="field"><label>Type</label><select id="destinationType"><option value="telegram">Telegram</option><option value="internal_webhook">Internal webhook</option><option value="audit_only">Audit only</option><option value="broker_account">Broker account record</option></select></div><div class="field"><label>Display name</label><input id="destinationName"></div><div class="field"><label>Destination reference</label><input id="destinationRef" placeholder="Channel/chat reference, HTTPS endpoint, or account reference"></div><div class="field"><label>Formatting template</label><select id="destinationTemplate"><option value="">No template</option></select></div><div class="field full"><label>Credential JSON</label><textarea id="destinationCredentials" rows="4" placeholder="Submitted once, encrypted server-side, never returned"></textarea></div><div class="full"><button class="btn primary" data-action="create-destination">Create disabled destination</button></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Type</th><th>Reference</th><th>State</th><th>Health</th><th>Credentials</th><th>Actions</th></tr></thead><tbody id="destinationRows"><tr><td colspan="7" class="empty">Connect to load destinations.</td></tr></tbody></table></div></div></section>
<section id="view-templates" class="view"><div class="card"><div class="toolbar"><div><h2 class="section-title">AI Formatting</h2><div class="muted">Presentation only. Trading semantics are protected by deterministic validation and fallback.</div></div><button class="btn primary" data-toggle="template-form">Add template</button></div><div id="template-form" class="form"><div class="form-grid"><div class="field"><label>Template name</label><input id="templateName"></div><div class="field"><label>Formatting mode</label><select id="formattingMode"><option value="none">none</option><option value="clean">clean</option><option value="template" selected>template</option><option value="ai_then_fallback">ai_then_fallback</option></select></div><div class="field"><label>Parse mode</label><select id="parseMode"><option>HTML</option><option>Markdown</option><option>MarkdownV2</option><option>plain</option></select></div><div class="field"><label>Brand name</label><input id="brandName"></div><div class="field"><label>Header</label><input id="templateHeader"></div><div class="field"><label>Footer</label><input id="templateFooter"></div><div class="field full"><label>Disclaimer</label><textarea id="templateDisclaimer" rows="3"></textarea></div><div class="full"><button class="btn primary" data-action="create-template">Create template</button></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Mode</th><th>Parse</th><th>Brand</th><th>Actions</th></tr></thead><tbody id="templateRows"><tr><td colspan="5" class="empty">Connect to load templates.</td></tr></tbody></table></div></div></section>
<section id="view-routes" class="view"><div class="card"><div class="toolbar"><div><h2 class="section-title">Source → Destination Routes</h2><div class="muted">Routes are workspace-qualified and inactive destinations are never delivered.</div></div><button class="btn primary" data-toggle="route-form">Add route</button></div><div id="route-form" class="form"><div class="form-grid"><div class="field"><label>Source</label><select id="routeSource"></select></div><div class="field"><label>Destination</label><select id="routeDestination"></select></div><div class="field"><label>Route name</label><input id="routeName"></div><div class="field"><label>Priority</label><input id="routePriority" type="number" value="100"></div><div class="full"><button class="btn primary" data-action="create-route">Create active route</button></div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Source</th><th>Destination</th><th>Priority</th><th>State</th><th>Actions</th></tr></thead><tbody id="routeRows"><tr><td colspan="6" class="empty">Connect to load routes.</td></tr></tbody></table></div></div></section>
<section id="view-mtproto" class="view"><div class="grid"><div class="card"><h2>External VM</h2><p class="small">Telegram account credentials stay entirely on the customer-managed VM. Mkety provides the source ID, internal handoff endpoint, signed payload contract, and recovery guidance. This console intentionally has no Telegram account credential fields for External VM mode.</p><div class="code">external_mtproto → /api/v1/internal/source-event</div></div><div class="card"><h2>Cloudflare Container / Durable Object</h2><p class="small">For Mkety-hosted listeners, credentials are accepted only through the protected source setup flow, encrypted server-side, and never returned to the browser after submission.</p><div class="code">cloudflare_container_mtproto\ncloudflare_do_mtproto\nSOURCE_EVENT_QUEUE + recovery cron</div></div></div></section>
<section id="view-risk" class="view"><div class="grid"><div class="card"><h2>Risk Inventory</h2><p class="small">Account inactive by default, execution disabled by default, kill switch on by default, symbol allowlists, lot/risk caps, daily loss limit, max open risk, duplicate prevention, and broker-side authority checks.</p><div class="notice ${broker ? 'error' : 'success'}">Broker execution remains disabled for this launch workflow${broker ? ' — runtime fuse is unexpectedly ON.' : '.'}</div></div><div class="card"><h2>Operations &amp; Audit</h2><p class="small">Inspect source receive, parse, route, format, destination delivery, broker block, retry, and failure classes from canonical admin APIs.</p><div class="code">/api/v1/admin/operations\n/api/v1/admin/events/{eventId}/audit</div></div><div class="card"><h2>Sources</h2><p class="small">Configure Telegram MTProto, TradingView webhook, source bridges, and custom signed API on the main workspace dashboard.</p><div class="code">/api/v1/admin/sources</div></div><div class="card"><h2>Domains</h2><p class="small">Customer hostnames are routing context only and must resolve to this same workspace after verification.</p><div class="code">/api/v1/admin/hostnames</div></div></div></section>
<section class="card"><h2>Mkety staff administration</h2><p class="small">Mkety staff access-code administration is separate from enterprise tenant mutation controls. Authorized staff use <a href="/mkety-admin/access-codes">/mkety-admin/access-codes</a>; this page never calls the staff access-code API.</p></section>
</main><script>
(function(){'use strict';
var runtime=${JSON.stringify(runtime)};var state={destinations:[],templates:[],routes:[],sources:[]};
var workspace=document.getElementById('workspaceId'),bearer=document.getElementById('bearer');workspace.value=localStorage.getItem('mketyLaunchWorkspace')||'';bearer.value=sessionStorage.getItem('mketyLaunchBearer')||'';
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function message(t,k){document.getElementById('message').innerHTML=t?'<div class="notice '+(k||'info')+'">'+e(t)+'</div>':''}
function auth(){var w=workspace.value.trim(),b=bearer.value.trim();if(!w)throw new Error('Workspace ID is required');if(!b)throw new Error('Trading bearer is required');return{w:w,b:b}}
async function api(path,options){options=options||{};var a=auth();var headers=Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':a.w,'Authorization':'Bearer '+a.b},options.headers||{});var r=await fetch(path,Object.assign({},options,{headers:headers}));var body;try{body=await r.json()}catch(_){body={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||body.ok===false)throw new Error(body.reason||body.error||('HTTP_'+r.status));return body}
function parseObject(id,optional){var raw=document.getElementById(id).value.trim();if(!raw)return optional?undefined:{};var value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Credential JSON must be an object');return value}
function options(rows,label){return rows.map(function(x){return '<option value="'+e(x.id)+'">'+e(label(x))+'</option>'}).join('')}
function renderSelectors(){document.getElementById('destinationTemplate').innerHTML='<option value="">No template</option>'+options(state.templates,function(x){return x.templateName});document.getElementById('routeDestination').innerHTML=options(state.destinations,function(x){return x.displayName+' ('+x.destinationType+')'});document.getElementById('routeSource').innerHTML=options(state.sources,function(x){return x.displayName||x.sourceInstanceId||x.id})}
function renderDestinations(){var el=document.getElementById('destinationRows');if(!state.destinations.length){el.innerHTML='<tr><td colspan="7" class="empty">No destinations configured.</td></tr>';return}el.innerHTML=state.destinations.map(function(x){return '<tr><td>'+e(x.displayName)+'</td><td>'+e(x.destinationType)+'</td><td>'+e(x.destinationRef||'—')+'</td><td><span class="badge">'+(x.enabled?'Enabled':'Disabled')+'</span></td><td>'+e(x.healthStatus||'—')+'</td><td>'+e(x.credentialConfigured?'Configured':'Not configured')+'</td><td><div class="actions"><button class="btn '+(x.enabled?'warn':'good')+'" data-action="destination-state" data-id="'+e(x.id)+'" data-enable="'+(!x.enabled)+'">'+(x.enabled?'Disable':'Enable')+'</button><button class="btn secondary" data-action="destination-credentials" data-id="'+e(x.id)+'">Replace credentials</button></div></td></tr>'}).join('')}
function renderTemplates(){var el=document.getElementById('templateRows');if(!state.templates.length){el.innerHTML='<tr><td colspan="5" class="empty">No templates configured.</td></tr>';return}el.innerHTML=state.templates.map(function(x){return '<tr><td>'+e(x.templateName)+'</td><td>'+e(x.formattingMode)+'</td><td>'+e(x.parseMode)+'</td><td>'+e(x.brandName||'—')+'</td><td><button class="btn secondary" data-action="template-edit" data-id="'+e(x.id)+'">Edit</button></td></tr>'}).join('')}
function renderRoutes(){var el=document.getElementById('routeRows');if(!state.routes.length){el.innerHTML='<tr><td colspan="6" class="empty">No routes configured.</td></tr>';return}el.innerHTML=state.routes.map(function(x){return '<tr><td>'+e(x.routeName||'—')+'</td><td>'+e(x.sourceConnectionId)+'</td><td>'+e(x.destinationId)+'</td><td>'+e(x.priority)+'</td><td>'+e(x.enabled?'Enabled':'Disabled')+'</td><td><button class="btn '+(x.enabled?'warn':'good')+'" data-action="route-state" data-id="'+e(x.id)+'" data-enable="'+(!x.enabled)+'">'+(x.enabled?'Disable':'Enable')+'</button></td></tr>'}).join('')}
function render(){renderDestinations();renderTemplates();renderRoutes();renderSelectors()}
async function refresh(){var responses=await Promise.all([api('/api/v1/admin/destinations'),api('/api/v1/admin/templates'),api('/api/v1/admin/routes'),api('/api/v1/admin/sources')]);state.destinations=responses[0].destinations||[];state.templates=responses[1].templates||[];state.routes=responses[2].routes||[];state.sources=responses[3].sources||[];render()}
async function connect(){try{var a=auth();localStorage.setItem('mketyLaunchWorkspace',a.w);sessionStorage.setItem('mketyLaunchBearer',a.b);message('Loading enterprise launch state...');await refresh();message('Launch console connected.','success')}catch(err){message('Connection failed: '+err.message,'error')}}
async function createDestination(){var body={destinationType:document.getElementById('destinationType').value,displayName:document.getElementById('destinationName').value.trim(),destinationRef:document.getElementById('destinationRef').value.trim()||null,templateId:document.getElementById('destinationTemplate').value||null,settings:{}};var credentials=parseObject('destinationCredentials',true);if(credentials)body.credentials=credentials;await api('/api/v1/admin/destinations',{method:'POST',body:JSON.stringify(body)});document.getElementById('destinationCredentials').value='';await refresh()}
function templateBody(){return{templateName:document.getElementById('templateName').value.trim(),formattingMode:document.getElementById('formattingMode').value,parseMode:document.getElementById('parseMode').value,brandName:document.getElementById('brandName').value.trim()||null,header:document.getElementById('templateHeader').value.trim()||null,footer:document.getElementById('templateFooter').value.trim()||null,disclaimer:document.getElementById('templateDisclaimer').value.trim()||null,emojiStyle:'standard',cleanupRules:{},layout:{},isDefault:false}}
async function createTemplate(){await api('/api/v1/admin/templates',{method:'POST',body:JSON.stringify(templateBody())});await refresh()}
async function createRoute(){await api('/api/v1/admin/routes',{method:'POST',body:JSON.stringify({sourceConnectionId:document.getElementById('routeSource').value,destinationId:document.getElementById('routeDestination').value,routeName:document.getElementById('routeName').value.trim()||null,priority:Number(document.getElementById('routePriority').value||100),filters:{}})});await refresh()}
async function destinationState(btn){await api('/api/v1/admin/destinations/'+encodeURIComponent(btn.dataset.id)+'/'+(btn.dataset.enable==='true'?'enable':'disable'),{method:'POST'});await refresh()}
async function routeState(btn){await api('/api/v1/admin/routes/'+encodeURIComponent(btn.dataset.id)+'/'+(btn.dataset.enable==='true'?'enable':'disable'),{method:'POST'});await refresh()}
async function replaceCredentials(btn){var raw=prompt('Paste replacement credential JSON. It will be encrypted server-side and not returned.');if(!raw)return;var credentials=JSON.parse(raw);if(!credentials||typeof credentials!=='object'||Array.isArray(credentials))throw new Error('Credential JSON must be an object');await api('/api/v1/admin/destinations/'+encodeURIComponent(btn.dataset.id)+'/credentials',{method:'PUT',body:JSON.stringify({credentials:credentials})});await refresh()}
async function editTemplate(btn){var current=state.templates.find(function(x){return x.id===btn.dataset.id});if(!current)return;var name=prompt('Template name',current.templateName);if(name===null)return;var body={templateName:name.trim(),formattingMode:current.formattingMode,parseMode:current.parseMode,brandName:current.brandName,header:current.header,footer:current.footer,disclaimer:current.disclaimer,emojiStyle:current.emojiStyle||'standard',cleanupRules:current.cleanupRules||{},layout:current.layout||{},isDefault:!!current.isDefault};await api('/api/v1/admin/templates/'+encodeURIComponent(current.id),{method:'PUT',body:JSON.stringify(body)});await refresh()}
async function act(fn){try{message('Saving...');await fn();message('Saved canonical server state.','success')}catch(err){message('Save failed: '+err.message,'error')}}
document.getElementById('connectBtn').addEventListener('click',connect);document.addEventListener('click',function(ev){var tab=ev.target.closest('[data-tab]');if(tab){document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x===tab)});document.querySelectorAll('.view').forEach(function(x){x.classList.remove('active')});document.getElementById('view-'+tab.dataset.tab).classList.add('active');return}var toggle=ev.target.closest('[data-toggle]');if(toggle){document.getElementById(toggle.dataset.toggle).classList.toggle('open');return}var btn=ev.target.closest('[data-action]');if(!btn)return;var a=btn.dataset.action;if(a==='create-destination')act(createDestination);else if(a==='create-template')act(createTemplate);else if(a==='create-route')act(createRoute);else if(a==='destination-state')act(function(){return destinationState(btn)});else if(a==='destination-credentials')act(function(){return replaceCredentials(btn)});else if(a==='route-state')act(function(){return routeState(btn)});else if(a==='template-edit')act(function(){return editTemplate(btn)})});
})();
</script></body></html>`;
}
