export function withTelegramBotSource(html) {
  const marker = '</body>';
  if (!String(html).includes(marker)) return String(html);
  const script = `<script>(function(){'use strict';
function q(id){return document.getElementById(id)}
function note(text,type){var el=q('workspaceMessage');if(!el)return;el.className='notice '+(type||'info');el.textContent=text}
function splitIds(value){return String(value||'').split(/[\\n,]+/).map(function(v){return v.trim()}).filter(Boolean)}
function auth(){return{workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function admin(path,options){options=options||{};var a=auth();if(!a.workspace||!a.bearer)throw new Error('Your session has expired. Sign in again.');var response=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':a.workspace,'Authorization':'Bearer '+a.bearer},options.headers||{})}));var body;try{body=await response.json()}catch(_){body={ok:false,reason:'NON_JSON_RESPONSE'}}if(!response.ok||body.ok===false)throw new Error(body.reason||('HTTP_'+response.status));return body}
function ensureOption(){var select=q('sourceProvider');if(!select||select.querySelector('option[value="telegram_bot_api"]'))return;var option=document.createElement('option');option.value='telegram_bot_api';option.textContent='Telegram Bot API (normal bot)';var external=select.querySelector('option[value="external_mtproto"]');if(external)external.insertAdjacentElement('beforebegin',option);else select.appendChild(option)}
function renderFields(){var select=q('sourceProvider'),host=q('enterpriseSourceExtras');if(!select||!host||select.value!=='telegram_bot_api')return;host.innerHTML='<div class="notice info"><b>Telegram Bot API source.</b> Add your bot token once. Mkety stores it encrypted and manages the webhook automatically when you click Connect. Telegram cannot choose your workspace, routes, accounts or execution settings.</div><div class="grid"><div class="field"><label>Bot token</label><input id="sourceBotToken" type="password" autocomplete="new-password" placeholder="123456:ABC..."></div><div class="field"><label>Allowed chat / channel IDs</label><input id="sourceBotChats" placeholder="-1001234567890, -1009876543210"></div></div><div class="muted small">Only updates from these persisted chat IDs are accepted. Normal messages, channel posts, edits and reply/follow-up context are supported.</div>'}
async function createBotSource(){var instance=(q('sourceInstance')&&q('sourceInstance').value.trim())||'',name=(q('sourceName')&&q('sourceName').value.trim())||'',token=(q('sourceBotToken')&&q('sourceBotToken').value.trim())||'',chats=splitIds(q('sourceBotChats')&&q('sourceBotChats').value),priority=Number((q('sourcePriority')&&q('sourcePriority').value)||0);if(!instance){note('Reference is required for this bot source.','error');return}if(!token){note('Telegram bot token is required.','error');return}if(!chats.length){note('Add at least one allowed Telegram chat or channel ID.','error');return}note('Saving Telegram Bot source securely...','info');try{await admin('/api/v1/admin/sources',{method:'POST',body:JSON.stringify({providerType:'telegram_bot_api',sourceFamily:'telegram',sourceType:'telegram_bot',sourceInstanceId:instance,displayName:name||instance,externalIdentity:instance,priority:priority,config:{chat_ids:chats},credentials:{botToken:token}})});if(q('sourceBotToken'))q('sourceBotToken').value='';note('Telegram Bot source saved. Click Connect below to register its webhook and start receiving signals.','success');if(q('refreshBtn'))q('refreshBtn').click()}catch(error){note('Telegram Bot source failed: '+String(error.message||error),'error')}}
function install(){ensureOption();var select=q('sourceProvider');if(select){select.addEventListener('change',function(){setTimeout(renderFields,0)},true);if(select.value==='telegram_bot_api')setTimeout(renderFields,0)}document.addEventListener('click',function(event){var button=event.target&&event.target.closest&&event.target.closest('#createSourceBtn');if(!button||!q('sourceProvider')||q('sourceProvider').value!=='telegram_bot_api')return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();createBotSource()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();</script>`;
  return String(html).replace(marker, `${script}${marker}`);
}
