export function withUserAcceptanceControls(html) {
  const script = `<script>(function(){
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function session(){return {workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function api(path,options){options=options||{};var s=session();if(!s.workspace||!s.bearer)throw new Error('Your session has expired. Sign in again.');var r=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':s.workspace,'Authorization':'Bearer '+s.bearer},options.headers||{})}));var b;try{b=await r.json()}catch(_){b={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||b.ok===false)throw new Error(b.reason||('HTTP_'+r.status));return b}
function note(text,type){var el=q('workspaceMessage');if(!el)return;el.className='notice '+(type||'info');el.textContent=text}
function exactLabel(){var sel=q('destinationTemplate');if(sel&&sel.options&&sel.options.length){sel.options[0].textContent='Forward as-is (original)';sel.options[0].title='No AI, no cleanup, no reformatting';var host=sel.closest('.field');if(host&&!q('exactForwardHelp')){var h=document.createElement('div');h.id='exactForwardHelp';h.className='muted small';h.textContent='Forward as-is: no AI, no cleanup, no reformatting. Text, spacing, capitalization, emojis and Telegram replies are preserved.';host.appendChild(h)}}}
function ensurePanels(){var rows=q('accountRows');if(rows&&!q('userAccountSettings')){var p=document.createElement('div');p.id='userAccountSettings';p.className='formbox';p.innerHTML='<b>Account trading settings</b><div class="muted small">Current configurable settings are shown here for every existing broker connection.</div><div id="userAccountSettingRows"></div>';rows.closest('.card').appendChild(p)}var dest=q('destinationList');if(dest&&!q('userDestinationFormatting')){var d=document.createElement('div');d.id='userDestinationFormatting';d.className='formbox';d.innerHTML='<b>Destination formatting</b><div class="muted small">Forward as-is means exact source text and Telegram reply/thread structure. Templates and AI remain independent options.</div><div id="userDestinationFormattingRows"></div>';dest.closest('.card').appendChild(d)}}
async function saveLot(id,input){var value=Number(input.value);if(!(value>0)){note('Fixed lot must be a positive number.','error');return}try{await api('/api/v1/admin/accounts/'+encodeURIComponent(id)+'/fixed-lot',{method:'POST',body:JSON.stringify({lotValue:value})});note('Fixed lot updated.','success');await refresh()}catch(e){note('Fixed lot update failed: '+String(e.message||e),'error')}}
async function setAutoTp(id,enabled){try{await api('/api/v1/admin/accounts/'+encodeURIComponent(id)+'/auto-tp-protection',{method:'POST',body:JSON.stringify({enabled:enabled})});note('Automatic TP protection updated.','success');await refresh()}catch(e){note('Automatic TP protection update failed: '+String(e.message||e),'error')}}
async function setEntryZone(id,mode){try{await api('/api/v1/admin/accounts/'+encodeURIComponent(id)+'/entry-zone-policy',{method:'POST',body:JSON.stringify({mode:mode})});note('Entry-zone policy updated.','success');await refresh()}catch(e){note('Entry-zone policy update failed: '+String(e.message||e),'error')}}
function entryZoneOptions(selected){var choices=[['market_if_inside','Market if inside; nearest boundary outside'],['midpoint','Midpoint'],['lower','Lower boundary'],['upper','Upper boundary'],['market_only','Market only']];return choices.map(function(x){return '<option value="'+x[0]+'"'+(x[0]===selected?' selected':'')+'>'+esc(x[1])+'</option>'}).join('')}
function accountRow(x){var id=esc(x.id),lot=Number(x.lotValue);if(!Number.isFinite(lot)||lot<=0)lot=0.01;var entryMode=(x.entryZonePolicy&&x.entryZonePolicy.mode)||'market_if_inside';return '<div class="formbox"><div class="toolbar"><div><b>'+esc(x.label||x.accountId)+'</b> <span class="pill">'+esc(x.platform)+'</span><div class="muted small">Account '+esc(x.accountId)+' • '+esc(x.active?'Active':'Inactive')+' • '+esc(x.executionEnabled?'Execution ON':'Execution OFF')+' • '+esc(x.killSwitch?'Kill switch ON':'Kill switch OFF')+'</div></div></div><div class="grid" style="margin-top:8px"><div class="field"><label>Fixed lot size</label><div class="actions"><input data-account-fixed-lot="'+id+'" type="number" min="0.001" step="0.001" value="'+esc(lot)+'" style="max-width:160px"><button class="btn secondary" data-account-save-lot="'+id+'">Save lot</button></div></div><div class="field"><label>Automatic TP protection</label><div class="actions"><span class="pill '+(x.autoTpProtection?'good':'')+'">'+esc(x.autoTpProtection?'ON':'OFF')+'</span><button class="btn secondary" data-account-auto-tp-protection="'+id+'" data-enable="'+(x.autoTpProtection?'0':'1')+'">'+esc(x.autoTpProtection?'Disable':'Enable')+'</button></div><div class="muted small">When enabled, TP-hit management protects remaining legs using break-even/progressive safety logic.</div></div><div class="field"><label>Fast entry</label><div class="actions"><span class="pill good">Always on</span></div><div class="muted small">Fast/incomplete entries execute immediately. This safety behavior is locked and has no off switch.</div></div><div class="field"><label>Entry-zone policy</label><div class="actions"><select data-entry-zone-select="'+id+'">'+entryZoneOptions(entryMode)+'</select><button class="btn secondary" data-account-save-entry-zone="'+id+'">Save entry policy</button></div><div class="muted small">Controls how a price range is materialized for this broker account.</div></div></div><details><summary>Current account policies</summary><pre class="code">'+esc(JSON.stringify({lotSizingType:x.lotSizingType,lotValue:x.lotValue,autoTpProtection:x.autoTpProtection,fastEntryPolicy:x.fastEntryPolicy||{enabled:true,mode:'execute_immediately',locked:true},entryZonePolicy:x.entryZonePolicy||{mode:'market_if_inside'},active:x.active,executionEnabled:x.executionEnabled,killSwitch:x.killSwitch},null,2))+'</pre></details></div>'}
function destinationRow(x,templates){var template=templates.find(function(t){return String(t.id)===String(x.templateId)});var mode=x.templateId?(template?(template.formattingMode||'template'):'template'):'Forward as-is (original)';var detail=x.templateId?(template?(template.templateName+' • '+mode):('Template '+x.templateId)):'No AI, no cleanup, no reformatting';return '<div class="formbox"><b>'+esc(x.displayName)+'</b> <span class="pill">'+esc(x.destinationType)+'</span><div class="muted small">'+esc(mode)+' • '+esc(detail)+'</div></div>'}
async function refresh(){ensurePanels();exactLabel();try{var results=await Promise.all([api('/api/v1/admin/accounts'),api('/api/v1/admin/destinations'),api('/api/v1/admin/templates')]);var accounts=results[0].accounts||[],destinations=results[1].destinations||[],templates=results[2].templates||[];var a=q('userAccountSettingRows');if(a)a.innerHTML=accounts.length?accounts.map(accountRow).join(''):'<div class="empty">No broker connections yet.</div>';var d=q('userDestinationFormattingRows');if(d)d.innerHTML=destinations.length?destinations.map(function(x){return destinationRow(x,templates)}).join(''):'<div class="empty">No destinations yet.</div>'}catch(e){}}
function bind(){document.addEventListener('click',function(ev){var t=ev.target&&ev.target.closest&&ev.target.closest('[data-account-save-lot]');if(t){ev.preventDefault();var input=document.querySelector('[data-account-fixed-lot="'+CSS.escape(t.dataset.accountSaveLot)+'"]');if(input)saveLot(t.dataset.accountSaveLot,input);return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-account-auto-tp-protection]');if(t){ev.preventDefault();setAutoTp(t.dataset.accountAutoTpProtection,t.dataset.enable==='1');return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-account-save-entry-zone]');if(t){ev.preventDefault();var select=document.querySelector('[data-entry-zone-select="'+CSS.escape(t.dataset.accountSaveEntryZone)+'"]');if(select)setEntryZone(t.dataset.accountSaveEntryZone,select.value)}})}
function init(){ensurePanels();exactLabel();bind();setTimeout(refresh,450);setTimeout(refresh,1700);var sel=q('destinationTemplate');if(sel)sel.addEventListener('change',exactLabel)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();</script>`;
  return String(html)
    .replace('<option value="">No template</option>', '<option value="">Forward as-is (original)</option>')
    .replace('</body>', script + '</body>');
}
