export function renderMketyAdminAccessCodesPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Mkety Staff Trading Admin</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#eef4ff;background:#07111f}
    body{margin:0;background:#07111f;color:#eef4ff}.wrap{max-width:1120px;margin:0 auto;padding:32px 20px 64px}h1{margin:0 0 8px;font-size:32px}.muted{color:#9fb2cc}.card{background:#0c1a2c;border:1px solid #203a59;border-radius:16px;padding:20px;margin-top:20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.field{display:flex;flex-direction:column;gap:6px}label{font-size:13px;color:#b9c9dd}input,select{background:#081522;color:#eef4ff;border:1px solid #2b496b;border-radius:10px;padding:10px 12px}button{border:0;border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer;background:#38a3ff;color:#04101c}.secondary{background:#17304b;color:#eef4ff}.danger{background:#8f3141;color:white}.success{background:#1c7d53;color:white}.live{background:#a26412;color:white}.checks{display:flex;flex-wrap:wrap;gap:12px;margin:16px 0}.checks label{display:flex;align-items:center;gap:7px;background:#0a1727;border:1px solid #203a59;border-radius:10px;padding:9px 11px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid #203a59;vertical-align:top}th{font-size:12px;color:#9fb2cc;text-transform:uppercase;letter-spacing:.04em}.once{margin-top:14px;padding:13px;border-radius:10px;background:#0d2b20;border:1px solid #27694e;display:none;word-break:break-all}.error{color:#ff9ca8;margin-top:10px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.status{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.pill{padding:7px 10px;border-radius:999px;background:#15283e;border:1px solid #294765;font-size:13px}.warning{padding:12px;border-radius:10px;background:#2c2410;border:1px solid #725a1e;color:#ffe5a6}.okbox{padding:12px;border-radius:10px;background:#0d2b20;border:1px solid #27694e;color:#b9f4d6}.controlgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.control{background:#081522;border:1px solid #203a59;border-radius:12px;padding:16px}.control h3{margin:0 0 6px}.critical{border-color:#725a1e}
  </style>
</head>
<body><main class="wrap">
<h1>Mkety Staff Trading Admin</h1><p class="muted">Manage enterprise access and persisted runtime controls. Changes below take effect without rebuilding or redeploying the Worker. The staff secret stays only in memory for this page session.</p>
<section class="card"><div class="field"><label for="staffSecret">Mkety Trading admin secret (memory only)</label><input id="staffSecret" type="password" autocomplete="off" placeholder="Enter MKETY_TRADING_ADMIN_SECRET" /></div><div class="toolbar"><button class="secondary" id="refreshBtn" type="button">Refresh admin state</button></div><div id="pageError" class="error" role="alert"></div></section>

<section class="card"><h2>Runtime master controls</h2><p class="muted">These are database-authoritative operational switches. Demo execution never requires the Live / Real-Money switch.</p>
<div class="controlgrid">
  <div class="control"><h3>Global Trading Access</h3><div class="status"><span class="pill" id="tradingStatus">Unknown</span></div><p class="muted">OFF stops production trading ingress, connection administration, queues and broker execution while leaving health/login/staff administration available.</p><div class="toolbar"><button class="danger" id="disableTradingBtn">Turn Trading Access OFF</button><button class="success" id="enableTradingBtn">Turn Trading Access ON</button></div></div>
  <div class="control"><h3>Global Broker Execution</h3><div class="status"><span class="pill" id="brokerStatus">Unknown</span><span class="pill" id="effectiveStatus">Effective: unknown</span></div><p class="muted">OFF blocks every broker dispatch for both demo and live accounts. It does not require a redeploy.</p><div class="toolbar"><button class="danger" id="disableBrokerBtn">Turn Broker Execution OFF</button><button class="success" id="enableBrokerBtn">Turn Broker Execution ON</button></div></div>
  <div class="control critical"><h3>Global Live / Real-Money Execution</h3><div class="status"><span class="pill" id="liveStatus">Unknown</span><span class="pill" id="effectiveLiveStatus">Effective live: unknown</span></div><p class="muted">Keep OFF for demo testing. A live account still needs its own per-account Live Execution switch ON, normal Execution ON, Active ON, Kill Switch OFF and every route/risk/symbol gate to pass.</p><div class="toolbar"><button class="danger" id="disableLiveBtn">Turn Live / Real-Money OFF</button><button class="live" id="enableLiveBtn">Enable Live / Real-Money</button></div></div>
</div><div id="runtimeMessage" class="warning">Enter the admin secret and refresh before changing runtime controls.</div></section>

<section class="card"><h2>Create or reissue access code</h2><p class="muted">Leave Existing workspace ID blank for a new customer. For a returning owner on a new browser/device, paste their existing workspace ID to issue a replacement one-time code without creating another workspace.</p>
<div class="grid"><div class="field"><label for="ownerEmail">Owner email</label><input id="ownerEmail" type="email" /></div><div class="field"><label for="ownerName">Owner name</label><input id="ownerName" /></div><div class="field"><label for="workspaceName">Workspace name</label><input id="workspaceName" /></div><div class="field"><label for="workspaceId">Existing workspace ID (optional)</label><input id="workspaceId" placeholder="Reuse only for access reissue" /></div><div class="field"><label for="expiresAt">Code expires at</label><input id="expiresAt" type="datetime-local" /></div></div>
<div class="checks"><label><input id="tradingExecutionDestination" type="checkbox" checked /> Trading execution destination</label><label><input id="telegramDestination" type="checkbox" /> Telegram destination</label><label><input id="customSubdomain" type="checkbox" /> Custom subdomain</label><label><input id="customHostname" type="checkbox" /> Custom hostname</label></div>
<div class="toolbar"><button class="secondary preset" type="button" data-preset="trading">Trading Only</button><button class="secondary preset" type="button" data-preset="tradingTelegram">Trading + Telegram</button><button class="secondary preset" type="button" data-preset="full">Full Access</button><button id="createBtn" type="button">Create access code</button></div><div id="plainCode" class="once"></div></section>
<section class="card"><h2>Issued access codes</h2><p class="muted">Use Reissue to prepare the form for the same workspace. Plaintext codes are shown only once.</p><table><thead><tr><th>Workspace</th><th>Owner</th><th>Status</th><th>Entitlements</th><th>Expires</th><th>Action</th></tr></thead><tbody id="rows"><tr><td colspan="6" class="muted">Enter the staff secret and refresh.</td></tr></tbody></table></section>
</main>
<script>(()=>{
const API='/api/v1/mkety-admin/access-codes',RUNTIME_API='/api/v1/mkety-admin/runtime-controls',$=(id)=>document.getElementById(id);let accessRows=[];
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(ch)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const staffHeaders=(json=false)=>{const h={'X-Mkety-Admin-Secret':$('staffSecret').value};if(json)h['Content-Type']='application/json';return h};
const setError=(m='')=>{$('pageError').textContent=m};
async function request(path,opt={}){const r=await fetch(path,opt);let b={};try{b=await r.json()}catch{}if(!r.ok||!b.ok)throw new Error(b.reason||('HTTP '+r.status));return b}
function renderRuntime(b){
 const trading=b.tradingAccessEnabled===true,broker=b.brokerExecutionEnabled===true,live=b.liveBrokerExecutionEnabled===true,effective=b.effectiveBrokerExecutionEnabled===true,effectiveLive=b.effectiveLiveBrokerExecutionEnabled===true;
 $('tradingStatus').textContent='Trading Access: '+(trading?'ON':'OFF');$('brokerStatus').textContent='Broker Execution: '+(broker?'ON':'OFF');$('effectiveStatus').textContent='Effective: '+(effective?'ON':'BLOCKED');$('liveStatus').textContent='Live / Real-Money: '+(live?'ON':'OFF');$('effectiveLiveStatus').textContent='Effective live: '+(effectiveLive?'ON':'BLOCKED');
 $('runtimeMessage').className=effectiveLive?'warning':'okbox';$('runtimeMessage').textContent=effectiveLive?'LIVE / REAL-MONEY EXECUTION IS ARMED GLOBALLY. Live accounts still require their own Live Execution switch and all remaining safety gates.':effective?'Broker execution is available for eligible DEMO accounts. Live / Real-Money remains blocked globally.':'Broker dispatch is blocked by the current persisted runtime controls.';
}
async function refreshRuntime(){renderRuntime(await request(RUNTIME_API,{headers:staffHeaders()}))}
async function setControl(key,next){setError();if(key==='liveBrokerExecutionEnabled'&&next&&!confirm('Enable GLOBAL LIVE / REAL-MONEY execution? Only do this after all demo acceptance tests have passed.'))return;if(key==='brokerExecutionEnabled'&&next&&!confirm('Enable broker execution globally?'))return;if(key==='tradingAccessEnabled'&&!next&&!confirm('Turn global Trading Access OFF? This blocks production trading ingress and execution.'))return;try{renderRuntime(await request(RUNTIME_API,{method:'PATCH',headers:staffHeaders(true),body:JSON.stringify({[key]:next})}))}catch(e){setError(e.message)}}
const entitlementSummary=(ent={})=>{const a=[];if(ent.tradingExecutionDestination)a.push('Trading execution');if(ent.telegramDestination||(Array.isArray(ent.destinations)&&ent.destinations.includes('telegram')))a.push('Telegram');if(ent.customSubdomain)a.push('Subdomain');if(ent.customHostname)a.push('Hostname');return a.length?a.join(', '):'Restricted'};
async function refreshCodes(){const b=await request(API,{headers:staffHeaders()});accessRows=b.accessCodes||[];$('rows').innerHTML=accessRows.length?accessRows.map((i)=>'<tr><td><b>'+esc(i.workspaceDisplayName||i.workspaceId)+'</b><div class="muted">'+esc(i.workspaceId||'')+'</div></td><td>'+esc(i.ownerEmail||'')+'</td><td>'+esc(i.status||'')+'</td><td>'+esc(entitlementSummary(i.entitlements))+'</td><td>'+esc(i.expiresAt||'')+'</td><td><div class="toolbar"><button class="secondary reissue" data-id="'+esc(i.id)+'">Reissue</button>'+(i.status==='active'?'<button class="danger revoke" data-id="'+esc(i.id)+'">Revoke</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="6" class="muted">No access codes.</td></tr>'}
async function refresh(){setError();try{await Promise.all([refreshCodes(),refreshRuntime()])}catch(e){setError(e.message)}}
function applyPreset(n){const f=n==='full';$('tradingExecutionDestination').checked=true;$('telegramDestination').checked=n==='tradingTelegram'||f;$('customSubdomain').checked=f;$('customHostname').checked=f}
function applyEntitlements(ent={}){$('tradingExecutionDestination').checked=ent.tradingExecutionDestination===true;$('telegramDestination').checked=ent.telegramDestination===true||(Array.isArray(ent.destinations)&&ent.destinations.includes('telegram'));$('customSubdomain').checked=ent.customSubdomain===true;$('customHostname').checked=ent.customHostname===true}
function prepareReissue(id){const i=accessRows.find((x)=>String(x.id)===String(id));if(!i)return;$('ownerEmail').value=i.ownerEmail||'';$('ownerName').value=i.ownerName||'';$('workspaceName').value=i.workspaceDisplayName||'';$('workspaceId').value=i.workspaceId||'';$('expiresAt').value='';applyEntitlements(i.entitlements||{});$('plainCode').style.display='none';window.scrollTo({top:$('ownerEmail').getBoundingClientRect().top+window.scrollY-80,behavior:'smooth'})}
async function createCode(){setError();$('plainCode').style.display='none';const ev=$('expiresAt').value;const p={ownerEmail:$('ownerEmail').value,ownerName:$('ownerName').value,workspaceName:$('workspaceName').value,workspaceId:$('workspaceId').value.trim()||undefined,expiresAt:ev?new Date(ev).toISOString():undefined,entitlements:{tradingExecutionDestination:$('tradingExecutionDestination').checked,telegramDestination:$('telegramDestination').checked,customSubdomain:$('customSubdomain').checked,customHostname:$('customHostname').checked,destinations:[...($('tradingExecutionDestination').checked?['broker_account']:[]),...($('telegramDestination').checked?['telegram']:[]),'audit_only'],sourceTypes:['telegram','tradingview'],brokerModes:['demo'],liveExecution:false,maxTeamMembers:1}};try{const b=await request(API,{method:'POST',headers:staffHeaders(true),body:JSON.stringify(p)});$('plainCode').textContent='Shown once — copy now: '+b.accessCode.plainCode;$('plainCode').style.display='block';await refreshCodes()}catch(e){setError(e.message)}}
document.querySelectorAll('.preset').forEach((b)=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));$('refreshBtn').addEventListener('click',refresh);$('createBtn').addEventListener('click',createCode);$('disableTradingBtn').addEventListener('click',()=>setControl('tradingAccessEnabled',false));$('enableTradingBtn').addEventListener('click',()=>setControl('tradingAccessEnabled',true));$('disableBrokerBtn').addEventListener('click',()=>setControl('brokerExecutionEnabled',false));$('enableBrokerBtn').addEventListener('click',()=>setControl('brokerExecutionEnabled',true));$('disableLiveBtn').addEventListener('click',()=>setControl('liveBrokerExecutionEnabled',false));$('enableLiveBtn').addEventListener('click',()=>setControl('liveBrokerExecutionEnabled',true));
$('rows').addEventListener('click',async(e)=>{const r=e.target.closest('.reissue');if(r){prepareReissue(r.dataset.id);return}const b=e.target.closest('.revoke');if(!b)return;setError();try{await request(API+'/'+encodeURIComponent(b.dataset.id)+'/revoke',{method:'POST',headers:staffHeaders()});await refreshCodes()}catch(err){setError(err.message)}});
})();</script></body></html>`;
}
