export function withCTraderCbotConnections(html) {
  const script = `<script>(function(){
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function session(){return {workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function cbotApi(path,options){options=options||{};var s=session();if(!s.workspace||!s.bearer)throw new Error('Your session has expired. Sign in again.');var r=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':s.workspace,'Authorization':'Bearer '+s.bearer},options.headers||{})}));var b;try{b=await r.json()}catch(_){b={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||b.ok===false)throw new Error(b.reason||('HTTP_'+r.status));return b}
function roles(){var out=[];if(q('connectionRoleSource')&&q('connectionRoleSource').checked)out.push('source');if(q('connectionRoleExecution')&&q('connectionRoleExecution').checked)out.push('execution');return out.length?out:['execution']}
function notice(text,type){var e=q('unifiedConnectionMessage');if(!e)return;e.className='notice '+(type||'info');e.textContent=text}
function oneTime(title,text){var box=q('oneTimeConnectionSecret');if(!box)return;box.innerHTML='<div class="notice success"><b>'+esc(title)+'</b><div class="small">This connection token is shown once. Add it to the cTrader Cloud cBot now.</div></div><pre class="code">'+esc(text)+'</pre>'}
function showCbotForm(){var f=q('mt5ConnectionForm');if(!f)return;f.innerHTML='<div class="formbox"><h4 style="margin-top:0">Cloud Auto Trader</h4><div class="notice info small">Run Mkety Cloud Auto Trader in cTrader Cloud. No customer VPS is required. Creating the connection does not activate trading; the account remains inactive, execution-disabled and kill-switched until explicitly enabled.</div><div class="grid"><div class="field"><label>Connection label</label><input id="ctraderCbotLabel" placeholder="Main cTrader Cloud"></div><div class="field"><label>Environment</label><select id="ctraderCbotEnvironment"><option value="demo">Demo</option><option value="live">Live</option></select></div></div><button id="createCTraderCbotBtn" class="btn primary">Create Cloud Auto Trader connection</button></div>';q('createCTraderCbotBtn').onclick=createCbot}
async function createCbot(){var label=(q('ctraderCbotLabel').value||'').trim();if(!label){notice('Enter a label for this cTrader Cloud connection.','error');return}try{var x=await cbotApi('/api/v1/admin/connections/ctrader/cbot',{method:'POST',body:JSON.stringify({label:label,environment:q('ctraderCbotEnvironment').value,roles:roles()})});oneTime('Cloud Auto Trader connection created','WebSocket: '+x.gatewayWebSocketUrl+'\\nConnection token: '+x.oneTimeConnectionToken+'\\nExpires: '+x.connectionTokenExpiresAt+'\\n\\nAdd the WebSocket URL and connection token to Mkety Cloud Auto Trader in cTrader Cloud, start the cBot, then click Sync cBot identity.');notice('Cloud Auto Trader pairing created. Start the cBot in cTrader Cloud, then sync the authenticated account identity.','success');attachSyncButtons()}catch(e){notice('Cloud Auto Trader setup failed: '+String(e.message||e),'error')}}
async function syncCbot(id,button){if(button)button.disabled=true;try{var x=await cbotApi('/api/v1/admin/connections/ctrader/cbot/'+encodeURIComponent(id)+'/sync',{method:'POST',body:'{}'});notice('Cloud Auto Trader connected to cTrader account '+String(x.account&&x.account.accountId||'')+'. Trading safety controls remain unchanged.','success');if(button){button.textContent='Identity synced';button.disabled=true}}catch(e){notice('Cloud Auto Trader sync failed: '+String(e.message||e),'error');if(button)button.disabled=false}}
function attachSyncButtons(){document.querySelectorAll('[data-account-edit]').forEach(function(edit){var id=edit.getAttribute('data-account-edit');var card=edit.closest('.formbox');if(!id||!card||card.querySelector('[data-cbot-sync]'))return;if(card.textContent.indexOf('ctrader_cbot')<0)return;var actions=edit.closest('.actions')||card;var b=document.createElement('button');b.className='btn secondary';b.type='button';b.textContent='Sync cBot identity';b.setAttribute('data-cbot-sync',id);b.onclick=function(){syncCbot(id,b)};actions.insertBefore(b,edit)})}
function install(){var direct=q('connectCTraderBtn');if(direct){direct.textContent='Direct Connection — Recommended';direct.title='Connect cTrader through the recommended Open API authorization flow';if(!q('connectCTraderCbotBtn')){var b=document.createElement('button');b.id='connectCTraderCbotBtn';b.className='btn secondary';b.type='button';b.textContent='Cloud Auto Trader';b.title='Connect through Mkety Cloud Auto Trader running in cTrader Cloud';b.onclick=showCbotForm;direct.parentNode.insertBefore(b,direct.nextSibling)}}attachSyncButtons();var root=q('unifiedConnectionsPanel');if(root&&typeof MutationObserver!=='undefined'){new MutationObserver(attachSyncButtons).observe(root,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,0)});else setTimeout(install,0);
})();</script>`;
  const source = String(html ?? '');
  return source.includes('</body>') ? source.replace('</body>', `${script}</body>`) : `${source}${script}`;
}
