export function withMt5ConnectorConnections(html) {
  const script = `<script>(function(){
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function session(){return {workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function mt5Api(path,options){options=options||{};var s=session();if(!s.workspace||!s.bearer)throw new Error('Your session has expired. Sign in again.');var r=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':s.workspace,'Authorization':'Bearer '+s.bearer},options.headers||{})}));var b;try{b=await r.json()}catch(_){b={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||b.ok===false)throw new Error(b.reason||('HTTP_'+r.status));return b}
function notice(text,type){var e=q('unifiedConnectionMessage');if(!e)return;e.className='notice '+(type||'info');e.textContent=text}
function roles(){var out=[];if(q('connectionRoleSource')&&q('connectionRoleSource').checked)out.push('source');if(q('connectionRoleExecution')&&q('connectionRoleExecution').checked)out.push('execution');return out.length?out:['execution']}
function oneTime(title,text){var box=q('oneTimeConnectionSecret');if(!box)return;box.innerHTML='<div class="notice success"><b>'+esc(title)+'</b><div class="small">This one-time pairing token is shown once. Paste it into Mkety MT5 Connector on the Windows computer running the target MT5 terminal.</div></div><pre class="code">'+esc(text)+'</pre>'}
function showConnector(){var f=q('mt5ConnectionForm');if(!f)return;f.innerHTML='<div class="formbox"><h4 style="margin-top:0">MT5 Connector — Recommended</h4><div class="notice info small"><b>No customer VPS or public inbound URL is required.</b> Keep the Windows PC and MetaTrader 5 terminal running whenever automated execution is expected. The connector opens an outbound encrypted WebSocket to Mkety and reads the actual logged-in MT5 account, broker server and available symbols directly from the terminal.</div><div class="actions" style="margin:10px 0"><a class="btn secondary" href="https://github.com/MketyDigital/Trading/releases/download/mt5-connector-v1.0.0/MketyMT5Connector.exe" target="_blank" rel="noopener noreferrer">Download Mkety MT5 Connector</a></div><div class="grid"><div class="field"><label>Connection label</label><input id="mt5ConnectorLabel" placeholder="Main MT5 account"></div><div class="field"><label>Expected environment</label><select id="mt5ConnectorEnvironment"><option value="demo">Demo</option><option value="live">Live</option></select></div></div><button id="createMt5ConnectorBtn" class="btn primary" type="button">Create MT5 Connector pairing</button><div class="muted small" style="margin-top:8px">After creation: open the downloaded connector, paste the WebSocket URL (wss://...) and one-time token, start it while MT5 is logged into the intended account, then click <b>Sync MT5 identity</b> on the account card.</div></div>';q('createMt5ConnectorBtn').onclick=createConnector}
async function createConnector(){var label=(q('mt5ConnectorLabel').value||'').trim();if(!label){notice('Enter a label for this MT5 connection.','error');return}try{var x=await mt5Api('/api/v1/admin/connections/mt5/connector',{method:'POST',body:JSON.stringify({label:label,environment:q('mt5ConnectorEnvironment').value,roles:roles()})});oneTime('MT5 Connector pairing created','WebSocket: '+x.gatewayWebSocketUrl+'\\nConnection token: '+x.oneTimeConnectionToken+'\\nExpires: '+x.connectionTokenExpiresAt+'\\n\\n1. Open MT5 and log into the intended account.\\n2. Run MketyMT5Connector.exe.\\n3. Paste this WebSocket URL and token.\\n4. Return to Mkety and click Sync MT5 identity.');notice('MT5 Connector pairing created. Start the connector on the target Windows MT5 terminal, then sync identity.','success');attachSyncButtons()}catch(e){notice('MT5 Connector setup failed: '+String(e.message||e),'error')}}
async function syncConnector(id,button){if(button)button.disabled=true;try{var x=await mt5Api('/api/v1/admin/connections/mt5/connector/'+encodeURIComponent(id)+'/sync',{method:'POST',body:'{}'});var a=x.account||{};notice('MT5 Connector connected to account '+String(a.accountId||'')+(a.serverName?' on '+a.serverName:'')+'. Existing account execution and risk controls are unchanged.','success');if(button){button.textContent='MT5 identity synced';button.disabled=true}}catch(e){notice('MT5 Connector sync failed: '+String(e.message||e),'error');if(button)button.disabled=false}}
function attachSyncButtons(){document.querySelectorAll('[data-account-edit]').forEach(function(edit){var id=edit.getAttribute('data-account-edit');var card=edit.closest('.formbox');if(!id||!card||card.querySelector('[data-mt5-connector-sync]'))return;if(card.textContent.indexOf('mt5_connector')<0)return;var actions=edit.closest('.actions')||card;var b=document.createElement('button');b.className='btn secondary';b.type='button';b.textContent='Sync MT5 identity';b.setAttribute('data-mt5-connector-sync',id);b.onclick=function(){syncConnector(id,b)};actions.insertBefore(b,edit)})}
function addAdvancedBridgeButton(primary){if(!primary||q('showAdvancedMt5BridgeBtn'))return;var advanced=document.createElement('button');advanced.id='showAdvancedMt5BridgeBtn';advanced.className='btn secondary';advanced.type='button';advanced.textContent='Advanced HTTP Bridge';advanced.title='Compatibility route for existing operator-managed HTTP bridge installations';advanced.onclick=function(){var original=q('showMt5BridgeBtn');var handler=original&&original.__mketyLegacyBridgeHandler;if(handler)return handler();notice('Advanced HTTP Bridge is retained only for existing compatibility deployments. New customers should use MT5 Connector.','info')};primary.parentNode.insertBefore(advanced,primary.nextSibling)}
function install(){var bridge=q('showMt5BridgeBtn');if(bridge){if(!bridge.__mketyLegacyBridgeHandler)bridge.__mketyLegacyBridgeHandler=bridge.onclick;bridge.textContent='MT5 Connector — Recommended';bridge.title='Outbound connector; no customer VPS, inbound firewall or public bridge URL required';bridge.onclick=showConnector;addAdvancedBridgeButton(bridge)}var cloud=q('showMt5CloudBtn');if(cloud)cloud.style.display='none';var readiness=q('connectionReadiness');if(readiness){var current=readiness.textContent||'';readiness.textContent=current.replace(/MT5 Bridge:[^•]*/,'MT5 Connector: Ready when shared gateway is configured ').replace(/• MT5 Cloud:.*/,'')}attachSyncButtons();var root=q('unifiedConnectionsPanel');if(root&&typeof MutationObserver!=='undefined'){new MutationObserver(attachSyncButtons).observe(root,{childList:true,subtree:true})}}
function scheduleInstall(){setTimeout(install,25);setTimeout(install,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scheduleInstall);else scheduleInstall();
})();</script>`;
  const source = String(html ?? '');
  return source.includes('</body>') ? source.replace('</body>', `${script}</body>`) : `${source}${script}`;
}
