export function withGranularRoutingConsole(html) {
  const marker = '</body>';
  if (!String(html).includes(marker)) return String(html);
  const panel = `<section id="granularRoutingPanel" class="card" style="margin-top:18px">
  <h3>Source routing</h3>
  <p class="muted small">Existing routes use this same editor. Choose the source, select the exact channels/feeds allowed to reach a destination, and save. Sources, destinations, credentials and accounts are not recreated when you edit a route.</p>
  <div class="grid">
    <div class="formbox">
      <b>Create or edit a route</b>
      <div class="field"><label>Existing route (optional)</label><select id="granularExistingRoute"><option value="">Create a new route</option></select></div>
      <div class="field"><label>Source connection</label><select id="granularRouteSource"><option value="">Loading sources…</option></select></div>
      <div class="field">
        <label><input id="granularAllChannels" type="checkbox"> All channels from this source</label>
        <div class="muted small">Use this only when every channel/feed under this source should reach the destination.</div>
      </div>
      <div class="field"><label>Allowed channels / feeds</label><div id="granularRouteFeeds" class="formbox" style="padding:8px"><span class="muted small">Choose a source first.</span></div></div>
      <div class="muted small"><b>Selective mode:</b> Only checked channels reach this destination. Unchecked channels are skipped for this route and do not fall back to an old all-channels route.</div>
      <div class="field"><label>Destination</label><select id="granularRouteDestination"><option value="">Loading destinations…</option></select></div>
      <div class="field"><label>Route name</label><input id="granularRouteName" placeholder="Main signals → Octa MT5"></div>
      <div class="grid">
        <div class="field"><label>Allowed canonical symbols (optional)</label><input id="granularAllowedSymbols" placeholder="XAUUSD, EURUSD"></div>
        <div class="field"><label>Blocked canonical symbols (optional)</label><input id="granularBlockedSymbols" placeholder="DERIV:VOLATILITY_75"></div>
      </div>
      <div class="muted small">Leave both symbol filters blank to allow every symbol this destination account can actually trade. Filters only narrow the destination account's real symbol capabilities; they never add unsupported symbols.</div>
      <div class="grid">
        <div class="field"><label>Priority</label><input id="granularRoutePriority" type="number" value="100"></div>
        <div class="field"><label><input id="granularRouteEnabled" type="checkbox" checked> Route enabled</label></div>
      </div>
      <div class="actions"><button id="granularSaveRoute" class="btn primary" type="button">Save route</button><button id="granularResetRoute" class="btn secondary" type="button">New route</button></div>
      <div id="granularRouteMessage" class="muted small" style="margin-top:7px"></div>
    </div>
    <div class="formbox">
      <b>Reusable Telegram delivery bot</b>
      <div class="muted small">Save a BotFather token once, then reuse it for any number of destination channels where that bot is an admin. Rename and token rotation are separate operations.</div>
      <div class="field"><label>New bot connection name</label><input id="granularBotName" placeholder="Starpips delivery bot"></div>
      <div class="field"><label>Bot token</label><input id="granularBotToken" type="password" autocomplete="new-password" placeholder="123456:ABC..."></div>
      <button id="granularCreateBot" class="btn secondary" type="button">Save new bot credential</button>
      <hr style="margin:14px 0">
      <div class="field"><label>Saved bot</label><select id="granularBotConnection"><option value="">No saved bot yet</option></select></div>
      <div class="actions"><button id="granularRenameBot" class="btn secondary" type="button">Rename bot</button><button id="granularRotateBot" class="btn secondary" type="button">Rotate token</button></div>
      <div id="granularBotMessage" class="muted small" style="margin-top:7px"></div>
    </div>
  </div>
  <div class="grid" style="margin-top:12px">
    <div class="formbox">
      <b>Create or edit Telegram channel endpoint</b>
      <div class="field"><label>Existing Telegram endpoint (optional)</label><select id="granularExistingTelegramDestination"><option value="">Create a new endpoint</option></select></div>
      <div class="field"><label>Saved bot</label><select id="granularEndpointBotConnection"><option value="">Select saved bot</option></select></div>
      <div class="field"><label>Destination channel name</label><input id="granularTelegramDestinationName" placeholder="VIP Gold"></div>
      <div class="field"><label>Destination chat/channel ID</label><input id="granularTelegramDestinationChat" placeholder="-1001234567890"></div>
      <div class="field"><label>Delivery formatting</label><select id="granularTelegramFormattingMode">
        <option value="inherit">Use saved template mode / existing default</option>
        <option value="none">Forward as-is (original)</option>
        <option value="clean">Clean original</option>
        <option value="template">Structured template</option>
        <option value="ai_then_fallback">AI presentation + safe fallback</option>
      </select></div>
      <div class="muted small" id="granularFormattingHelp">Forward as-is (original): No AI, no cleanup, no reformatting, no branding. Clean original: deterministic cleanup only. Structured template: deterministic configured layout. AI presentation + safe fallback: presentation AI only, with deterministic fallback and no authority to change trading meaning.</div>
      <div class="field"><label>Saved formatting template (optional)</label><select id="granularTelegramTemplate"><option value="">No saved custom template</option></select></div>
      <div class="actions"><button id="granularSaveTelegramDestination" class="btn secondary" type="button">Add Telegram channel endpoint</button><button id="granularResetTelegramDestination" class="btn secondary" type="button">New endpoint</button></div>
    </div>
    <div class="formbox"><b>Editable destinations</b><div class="muted small">Non-Telegram destinations can also be edited without recreation. Secrets are never changed by these controls.</div><div id="granularDestinationSummary" style="margin-top:8px"></div></div>
  </div>
  <div class="grid" style="margin-top:12px">
    <div class="formbox"><b>Source connections & feeds</b><div class="muted small">Edit source labels/priority/allowed chats or feed labels/state without creating a second source.</div><div id="granularFeedSummary" style="margin-top:8px">Loading…</div></div>
    <div class="formbox"><b>Formatting templates</b><div class="muted small">Templates keep their IDs and can be edited in place. Ready-made modes remain Forward as-is, Clean original, Structured template, and AI presentation + safe fallback.</div><div id="granularTemplateSummary" style="margin-top:8px">Loading…</div></div>
  </div>
</section>`;
  const script = `<script>(function(){'use strict';
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function auth(){return{workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function admin(path,options){options=options||{};var a=auth();if(!a.workspace||!a.bearer)throw new Error('Your session has expired. Sign in again.');var r=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':a.workspace,'Authorization':'Bearer '+a.bearer},options.headers||{})}));var b;try{b=await r.json()}catch(_){b={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||b.ok===false)throw new Error(b.reason||('HTTP_'+r.status));return b}
function ids(v){return Array.from(new Set(String(v||'').split(/[\\n,]+/).map(function(x){return x.trim().toUpperCase()}).filter(Boolean)))}
function msg(id,text,ok){var el=q(id);if(!el)return;el.textContent=text;el.className=(ok?'notice success':'notice error')+' small'}
var state={sources:[],feedRows:[],destinations:[],connections:[],templates:[],logicalRoutes:[],editingRouteKey:null,editingRouteOriginal:null,editingTelegramDestination:null};
function button(label,attr,id){return '<button type="button" class="btn secondary" '+attr+'="'+esc(id)+'">'+esc(label)+'</button>'}
function sourceName(id){var s=state.sources.find(function(x){return x.id===id});return s?(s.displayName||s.sourceInstanceId||s.id):id}
function destinationName(id){var d=state.destinations.find(function(x){return x.id===id});return d?(d.displayName||d.id):id}
function sourceRow(id){return state.feedRows.find(function(row){return row.s.id===id})||null}
async function load(){var jobs=await Promise.allSettled([admin('/api/v1/admin/sources'),admin('/api/v1/admin/destinations'),admin('/api/v1/admin/destination-connections'),admin('/api/v1/admin/templates'),admin('/api/v1/admin/logical-routes')]);state.sources=jobs[0].status==='fulfilled'?(jobs[0].value.sources||[]):[];state.destinations=jobs[1].status==='fulfilled'?(jobs[1].value.destinations||[]):[];state.connections=jobs[2].status==='fulfilled'?(jobs[2].value.destinationConnections||[]):[];state.templates=jobs[3].status==='fulfilled'?(jobs[3].value.templates||[]):[];state.logicalRoutes=jobs[4].status==='fulfilled'?(jobs[4].value.logicalRoutes||[]):[];state.feedRows=await Promise.all(state.sources.map(async function(s){try{var r=await admin('/api/v1/admin/sources/'+encodeURIComponent(s.id)+'/feeds');return{s:s,feeds:r.feeds||[]}}catch(_){return{s:s,feeds:[]}}}));renderSources();renderRouteFeeds();renderDestinations();renderBots();renderTemplates();renderRoutes();renderSummary();renderDestinationSummary();renderTemplateSummary()}
function renderSources(){var el=q('granularRouteSource');if(!el)return;el.innerHTML='<option value="">Select source connection</option>'+state.sources.map(function(s){return '<option value="'+esc(s.id)+'">'+esc(s.displayName||s.sourceInstanceId||s.id)+'</option>'}).join('')}
function renderRouteFeeds(){var box=q('granularRouteFeeds');if(!box)return;var sourceId=q('granularRouteSource')&&q('granularRouteSource').value,row=sourceRow(sourceId),all=q('granularAllChannels')&&q('granularAllChannels').checked;if(!sourceId){box.innerHTML='<span class="muted small">Choose a source first.</span>';return}var feeds=row?(row.feeds||[]).filter(function(f){return f.isActive!==false}):[];if(!feeds.length){box.innerHTML='<span class="muted small">No active child feeds are materialized for this source. Use All channels from this source if connection-wide routing is intended.</span>';return}box.innerHTML=feeds.map(function(f){return '<label style="display:block;padding:4px 0"><input type="checkbox" data-route-feed="'+esc(f.id)+'" '+(all?'disabled':'')+'> '+esc(f.displayName||f.providerFeedId)+' <span class="muted small">('+esc(f.providerFeedId)+')</span></label>'}).join('')}
function selectedFeedIds(){return Array.from(document.querySelectorAll('#granularRouteFeeds [data-route-feed]:checked')).map(function(el){return el.getAttribute('data-route-feed')}).filter(Boolean)}
function setSelectedFeeds(feedIds){var wanted=new Set(feedIds||[]);document.querySelectorAll('#granularRouteFeeds [data-route-feed]').forEach(function(el){el.checked=wanted.has(el.getAttribute('data-route-feed'))})}
function renderDestinations(){var el=q('granularRouteDestination');if(el)el.innerHTML='<option value="">Select destination</option>'+state.destinations.map(function(d){return '<option value="'+esc(d.id)+'">'+esc(d.displayName)+' • '+esc(d.destinationType)+(d.enabled?'':' • disabled')+'</option>'}).join('');var telegram=state.destinations.filter(function(d){return d.destinationType==='telegram'}),existing=q('granularExistingTelegramDestination');if(existing)existing.innerHTML='<option value="">Create a new endpoint</option>'+telegram.map(function(d){return '<option value="'+esc(d.id)+'">'+esc(d.displayName)+' • '+esc(d.destinationRef||'')+'</option>'}).join('')}
function renderBots(){var active=state.connections.filter(function(x){return x.providerType==='telegram_bot_api'});['granularBotConnection','granularEndpointBotConnection'].forEach(function(id){var el=q(id);if(el)el.innerHTML='<option value="">Select saved bot</option>'+active.map(function(x){return '<option value="'+esc(x.id)+'">'+esc(x.displayName)+(x.enabled?'':' • disabled')+'</option>'}).join('')})}
function renderTemplates(){var el=q('granularTelegramTemplate');if(el)el.innerHTML='<option value="">No saved custom template</option>'+state.templates.map(function(t){return '<option value="'+esc(t.id)+'">'+esc(t.templateName)+' • '+esc(t.formattingMode)+'</option>'}).join('')}
function renderRoutes(){var el=q('granularExistingRoute');if(!el)return;el.innerHTML='<option value="">Create a new route</option>'+state.logicalRoutes.map(function(r){var scope=r.mode==='all'?'All channels':String((r.selectedFeedIds||[]).length)+' selected';return '<option value="'+esc(r.logicalRouteKey)+'">'+esc(r.routeName||sourceName(r.sourceConnectionId)+' → '+destinationName(r.destinationId))+' • '+esc(scope)+(r.enabled===false?' • disabled':'')+'</option>'}).join('');if(state.editingRouteKey)el.value=state.editingRouteKey}
function renderSummary(){var el=q('granularFeedSummary');if(!el)return;if(!state.feedRows.length){el.innerHTML='No source connections yet.';return}el.innerHTML=state.feedRows.map(function(row){var name=row.s.displayName||row.s.sourceInstanceId||row.s.id;var sourceButtons=button('Edit source','data-edit-source',row.s.id);var feeds=row.feeds.length?row.feeds.map(function(f){return '<div class="toolbar" style="padding:5px 0"><span class="pill">'+esc(f.displayName||f.providerFeedId)+(f.isActive===false?' • disabled':'')+'</span>'+button('Edit','data-edit-feed',row.s.id+'|'+f.id)+'</div>'}).join(''):'<div class="muted small">No materialized child feeds; existing connection-level routing remains available through All channels.</div>';return '<div class="formbox" style="margin:6px 0"><div class="toolbar"><div><b>'+esc(name)+'</b><div class="muted small">'+esc(row.s.providerType||'')+'</div></div>'+sourceButtons+'</div>'+feeds+'</div>'}).join('')}
function renderDestinationSummary(){var el=q('granularDestinationSummary');if(!el)return;el.innerHTML=state.destinations.length?state.destinations.map(function(d){return '<div class="toolbar" style="border-top:1px solid #e8edf4;padding:7px 0"><div><b>'+esc(d.displayName)+'</b><div class="muted small">'+esc(d.destinationType)+' • '+esc(d.destinationRef||'')+'</div></div>'+button('Edit','data-edit-destination',d.id)+'</div>'}).join(''):'<div class="empty">No destinations yet.</div>'}
function modeLabel(mode){return mode==='none'?'Forward as-is (original)':mode==='clean'?'Clean original':mode==='template'?'Structured template':mode==='ai_then_fallback'?'AI presentation + safe fallback':mode||'template'}
function renderTemplateSummary(){var el=q('granularTemplateSummary');if(!el)return;el.innerHTML=state.templates.length?state.templates.map(function(t){return '<div class="toolbar" style="border-top:1px solid #e8edf4;padding:7px 0"><div><b>'+esc(t.templateName)+'</b><div class="muted small">'+esc(modeLabel(t.formattingMode))+' • '+esc(t.parseMode)+'</div></div>'+button('Edit','data-edit-template',t.id)+'</div>'}).join(''):'<div class="empty">No saved custom templates yet. The four ready-made formatting modes above are still available.</div>'}
function resetRoute(){state.editingRouteKey=null;state.editingRouteOriginal=null;q('granularExistingRoute').value='';q('granularRouteSource').value='';q('granularAllChannels').checked=false;q('granularRouteDestination').value='';q('granularRouteName').value='';q('granularAllowedSymbols').value='';q('granularBlockedSymbols').value='';q('granularRoutePriority').value='100';q('granularRouteEnabled').checked=true;q('granularSaveRoute').textContent='Save route';renderRouteFeeds();msg('granularRouteMessage','',true)}
function loadRoute(key){var r=state.logicalRoutes.find(function(x){return x.logicalRouteKey===key});if(!r){resetRoute();return}state.editingRouteKey=key;state.editingRouteOriginal={sourceConnectionId:r.sourceConnectionId,destinationId:r.destinationId,routeIds:r.routeIds||[]};q('granularRouteSource').value=r.sourceConnectionId;q('granularAllChannels').checked=r.mode==='all';renderRouteFeeds();setSelectedFeeds(r.selectedFeedIds||[]);q('granularRouteDestination').value=r.destinationId;q('granularRouteName').value=r.routeName||'';q('granularAllowedSymbols').value=((r.filters||{}).allowedCanonicalSymbols||[]).join(', ');q('granularBlockedSymbols').value=((r.filters||{}).blockedCanonicalSymbols||[]).join(', ');q('granularRoutePriority').value=String(r.priority==null?100:r.priority);q('granularRouteEnabled').checked=r.enabled!==false;q('granularSaveRoute').textContent='Save route changes';msg('granularRouteMessage',r.legacyDefaultSuppressed?'A compatible legacy all-channels row is suppressed by selective routing and will be cleaned up when you save.':'',true)}
async function saveRoute(){var sourceId=q('granularRouteSource').value,destinationId=q('granularRouteDestination').value,name=q('granularRouteName').value.trim(),all=q('granularAllChannels').checked,feeds=selectedFeedIds();if(!sourceId||!destinationId){msg('granularRouteMessage','Choose a source connection and destination.',false);return}if(!all&&!feeds.length){msg('granularRouteMessage','Select at least one channel/feed, or choose All channels from this source.',false);return}var filters={},allowed=ids(q('granularAllowedSymbols').value),blocked=ids(q('granularBlockedSymbols').value);if(allowed.length)filters.allowedCanonicalSymbols=allowed;if(blocked.length)filters.blockedCanonicalSymbols=blocked;var payload={sourceConnectionId:sourceId,destinationId:destinationId,previousSourceConnectionId:state.editingRouteOriginal&&state.editingRouteOriginal.sourceConnectionId,previousDestinationId:state.editingRouteOriginal&&state.editingRouteOriginal.destinationId,previousRouteIds:state.editingRouteOriginal&&state.editingRouteOriginal.routeIds||[],mode:all?'all':'selective',selectedFeedIds:all?[]:feeds,routeName:name||null,priority:Number(q('granularRoutePriority').value||100),enabled:q('granularRouteEnabled').checked,filters:filters};try{await admin('/api/v1/admin/logical-routes/reconcile',{method:'POST',body:JSON.stringify(payload)});msg('granularRouteMessage',all?'Route saved: every channel from this source may reach this destination.':'Route saved: only the checked channels may reach this destination; all other channels are skipped.',true);resetRoute();await load()}catch(e){msg('granularRouteMessage','Route failed: '+String(e.message||e),false)}}
async function createBot(){var name=q('granularBotName').value.trim(),token=q('granularBotToken').value.trim();if(!name||!token){msg('granularBotMessage','Bot name and token are required.',false);return}try{await admin('/api/v1/admin/destination-connections',{method:'POST',body:JSON.stringify({providerType:'telegram_bot_api',displayName:name,credentials:{botToken:token}})});q('granularBotToken').value='';msg('granularBotMessage','Bot credential saved encrypted. Add one or more channel endpoints below.',true);await load()}catch(e){msg('granularBotMessage','Bot credential failed: '+String(e.message||e),false)}}
async function renameBot(){var id=q('granularBotConnection').value;if(!id){msg('granularBotMessage','Choose a saved bot first.',false);return}var current=state.connections.find(function(x){return x.id===id}),name=prompt('Bot connection name',current&&current.displayName||'');if(name===null)return;name=name.trim();if(!name)return;try{await admin('/api/v1/admin/destination-connections/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({displayName:name})});msg('granularBotMessage','Bot renamed. Token was not changed.',true);await load()}catch(e){msg('granularBotMessage','Rename failed: '+String(e.message||e),false)}}
async function rotateBot(){var id=q('granularBotConnection').value;if(!id){msg('granularBotMessage','Choose a saved bot first.',false);return}var token=prompt('Paste the replacement BotFather token. This explicitly rotates the saved credential.','');if(token===null)return;token=token.trim();if(!token)return;try{await admin('/api/v1/admin/destination-connections/'+encodeURIComponent(id)+'/credentials',{method:'PUT',body:JSON.stringify({credentials:{botToken:token}})});msg('granularBotMessage','Bot token rotated. Existing channel endpoints continue using this saved bot.',true)}catch(e){msg('granularBotMessage','Token rotation failed: '+String(e.message||e),false)}}
function resetTelegramDestination(){state.editingTelegramDestination=null;q('granularExistingTelegramDestination').value='';q('granularEndpointBotConnection').value='';q('granularTelegramDestinationName').value='';q('granularTelegramDestinationChat').value='';q('granularTelegramFormattingMode').value='inherit';q('granularTelegramTemplate').value='';q('granularSaveTelegramDestination').textContent='Add Telegram channel endpoint'}
function loadTelegramDestination(id){var d=state.destinations.find(function(x){return x.id===id});if(!d){resetTelegramDestination();return}state.editingTelegramDestination=id;q('granularEndpointBotConnection').value=d.credentialConnectionId||'';q('granularTelegramDestinationName').value=d.displayName||'';q('granularTelegramDestinationChat').value=d.destinationRef||'';q('granularTelegramTemplate').value=d.templateId||'';q('granularTelegramFormattingMode').value=(d.settings&&((d.settings.formattingMode)||(d.settings.formatting_mode)))||'inherit';q('granularSaveTelegramDestination').textContent='Save endpoint changes'}
async function saveTelegramDestination(){var credentialConnectionId=q('granularEndpointBotConnection').value,name=q('granularTelegramDestinationName').value.trim(),chat=q('granularTelegramDestinationChat').value.trim(),templateId=q('granularTelegramTemplate').value||null,formatMode=q('granularTelegramFormattingMode').value||'inherit';if(!name||!chat){msg('granularBotMessage','Enter a destination name and chat/channel ID.',false);return}if(!state.editingTelegramDestination&&!credentialConnectionId){msg('granularBotMessage','Choose a saved bot for a new endpoint.',false);return}var current=state.destinations.find(function(x){return x.id===state.editingTelegramDestination}),settings=Object.assign({},current&&current.settings||{});delete settings.formatting_mode;if(formatMode==='inherit')delete settings.formattingMode;else settings.formattingMode=formatMode;var payload={displayName:name,destinationRef:chat,templateId:templateId,credentialConnectionId:credentialConnectionId||null,settings:settings};try{if(state.editingTelegramDestination)await admin('/api/v1/admin/destinations/'+encodeURIComponent(state.editingTelegramDestination),{method:'PATCH',body:JSON.stringify(payload)});else await admin('/api/v1/admin/destinations',{method:'POST',body:JSON.stringify(Object.assign({destinationType:'telegram'},payload))});msg('granularBotMessage',state.editingTelegramDestination?'Telegram endpoint updated in place.':'Telegram channel endpoint saved. Enable it in Destination controls when ready.',true);resetTelegramDestination();await load()}catch(e){msg('granularBotMessage','Telegram endpoint failed: '+String(e.message||e),false)}}
async function editSource(id){var s=state.sources.find(function(x){return x.id===id});if(!s)return;var name=prompt('Source display name',s.displayName||s.sourceInstanceId||'');if(name===null)return;var priority=prompt('Priority',String(s.priority||0));if(priority===null)return;var payload={displayName:name.trim()||s.displayName||s.sourceInstanceId,priority:Number(priority)};if(!Number.isFinite(payload.priority)){alert('Priority must be a number.');return}var config=Object.assign({},s.config||{});if(Array.isArray(config.allowed_chat_ids)||Array.isArray(config.chat_ids)){var key=Array.isArray(config.allowed_chat_ids)?'allowed_chat_ids':'chat_ids';var chats=prompt('Allowed Telegram chat IDs (comma separated)',config[key].join(', '));if(chats===null)return;config[key]=String(chats).split(/[\\n,]+/).map(function(x){return x.trim()}).filter(Boolean);payload.config=config}try{await admin('/api/v1/admin/sources/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(payload)});await load()}catch(e){alert('Source edit failed: '+String(e.message||e))}}
async function editFeed(value){var p=String(value).split('|'),sourceId=p[0],feedId=p[1],row=state.feedRows.find(function(x){return x.s.id===sourceId}),f=row&&row.feeds.find(function(x){return x.id===feedId});if(!f)return;var name=prompt('Feed display name',f.displayName||f.providerFeedId||'');if(name===null)return;var status=prompt('Feed state: on or off',f.isActive===false?'off':'on');if(status===null)return;status=status.trim().toLowerCase();if(!['on','off'].includes(status)){alert('Use on or off.');return}try{await admin('/api/v1/admin/sources/'+encodeURIComponent(sourceId)+'/feeds/'+encodeURIComponent(feedId),{method:'PATCH',body:JSON.stringify({displayName:name.trim()||null,enabled:status==='on'})});await load()}catch(e){alert('Feed edit failed: '+String(e.message||e))}}
async function editDestination(id){var d=state.destinations.find(function(x){return x.id===id});if(!d)return;if(d.destinationType==='telegram'){q('granularExistingTelegramDestination').value=id;loadTelegramDestination(id);q('granularExistingTelegramDestination').scrollIntoView({behavior:'smooth',block:'center'});return}var name=prompt('Destination display name',d.displayName||'');if(name===null)return;var ref=prompt('Destination reference',d.destinationRef||'');if(ref===null)return;try{await admin('/api/v1/admin/destinations/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({displayName:name.trim()||d.displayName,destinationRef:ref.trim()||null})});await load()}catch(e){alert('Destination edit failed: '+String(e.message||e))}}
async function editTemplate(id){var t=state.templates.find(function(x){return x.id===id});if(!t)return;var name=prompt('Template name',t.templateName||'');if(name===null)return;var mode=prompt('Formatting mode: none = Forward as-is, clean = Clean original, template = Structured template, ai_then_fallback = AI presentation + safe fallback',t.formattingMode||'template');if(mode===null)return;var header=prompt('Header (blank clears it)',t.header||'');if(header===null)return;var footer=prompt('Footer (blank clears it)',t.footer||'');if(footer===null)return;var disclaimer=prompt('Disclaimer (blank clears it)',t.disclaimer||'');if(disclaimer===null)return;try{await admin('/api/v1/admin/templates/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({templateName:name.trim()||t.templateName,formattingMode:mode.trim(),header:header||null,footer:footer||null,disclaimer:disclaimer||null})});await load()}catch(e){alert('Template edit failed: '+String(e.message||e))}}
function bindDelegation(){document.addEventListener('click',function(ev){var t=ev.target&&ev.target.closest&&ev.target.closest('[data-edit-source]');if(t){ev.preventDefault();editSource(t.dataset.editSource);return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-edit-feed]');if(t){ev.preventDefault();editFeed(t.dataset.editFeed);return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-edit-destination]');if(t){ev.preventDefault();editDestination(t.dataset.editDestination);return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-edit-template]');if(t){ev.preventDefault();editTemplate(t.dataset.editTemplate)}})}
function install(){var panel=q('granularRoutingPanel');if(panel){var routeCard=q('routeList')&&q('routeList').closest('.card');var target=document.querySelector('main')||document.body;if(routeCard&&routeCard.parentNode)routeCard.insertAdjacentElement('afterend',panel);else if(target!==document.body)target.appendChild(panel)}var routeSelect=q('granularExistingRoute'),telegramSelect=q('granularExistingTelegramDestination'),sourceSelect=q('granularRouteSource'),allChannels=q('granularAllChannels');if(routeSelect)routeSelect.addEventListener('change',function(){this.value?loadRoute(this.value):resetRoute()});if(telegramSelect)telegramSelect.addEventListener('change',function(){this.value?loadTelegramDestination(this.value):resetTelegramDestination()});if(sourceSelect)sourceSelect.addEventListener('change',function(){renderRouteFeeds()});if(allChannels)allChannels.addEventListener('change',function(){renderRouteFeeds();if(!this.checked&&state.editingRouteKey){var r=state.logicalRoutes.find(function(x){return x.logicalRouteKey===state.editingRouteKey});if(r)setSelectedFeeds(r.selectedFeedIds||[])}});var bindings=[['granularSaveRoute',saveRoute],['granularResetRoute',resetRoute],['granularCreateBot',createBot],['granularRenameBot',renameBot],['granularRotateBot',rotateBot],['granularSaveTelegramDestination',saveTelegramDestination],['granularResetTelegramDestination',resetTelegramDestination]];bindings.forEach(function(pair){var el=q(pair[0]);if(el)el.addEventListener('click',pair[1])});bindDelegation();load().catch(function(e){var el=q('granularFeedSummary');if(el)el.textContent='Routing data unavailable: '+String(e.message||e)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();</script>`;
  return String(html).replace(marker, `${panel}${script}${marker}`);
}