export function withRoutingAiCompletion(html) {
  const script = `<script>(function(){
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function auth(){return {workspace:sessionStorage.getItem('mketyTradingWorkspace')||'',bearer:sessionStorage.getItem('mketyTradingBearer')||''}}
async function admin(path,options){options=options||{};var s=auth();if(!s.workspace||!s.bearer)throw new Error('Your session has expired. Sign in again.');var r=await fetch(path,Object.assign({},options,{headers:Object.assign({'Accept':'application/json','Content-Type':'application/json','X-Mkety-Workspace-Id':s.workspace,'Authorization':'Bearer '+s.bearer},options.headers||{})}));var b;try{b=await r.json()}catch(_){b={ok:false,reason:'NON_JSON_RESPONSE'}}if(!r.ok||b.ok===false)throw new Error(b.reason||('HTTP_'+r.status));return b}
function note(text,type){var el=q('workspaceMessage');if(!el)return;el.className='notice '+(type||'info');el.textContent=text}
function ensureAiPromptField(){if(q('aiPresentationPrompt'))return;var footer=q('templateFooter');if(!footer)return;var field=document.createElement('div');field.className='field';field.style.marginTop='10px';field.innerHTML='<label>AI rebranding/formatting instructions</label><textarea id="aiPresentationPrompt" rows="4" placeholder="Example: Use my concise VIP style, keep the layout clean, use my preferred labels and end with Trade responsibly."></textarea><div class="muted small">Presentation only. These instructions cannot change symbol, BUY/SELL side, order type, entry, stop loss, take profits, risk, routing or broker execution.</div>';var parent=footer.closest('.field');(parent||footer).insertAdjacentElement('afterend',field)}
function replaceTemplateCreate(){var btn=q('createTemplateBtn');if(!btn||btn.dataset.aiPromptBound==='1')return;var clone=btn.cloneNode(true);clone.dataset.aiPromptBound='1';btn.replaceWith(clone);clone.addEventListener('click',async function(ev){ev.preventDefault();var name=(q('templateName')&&q('templateName').value.trim())||'';if(!name){note('Template name is required.','error');return}var instructions=(q('aiPresentationPrompt')&&q('aiPresentationPrompt').value.trim())||'';var payload={templateName:name,formattingMode:(q('formattingMode')&&q('formattingMode').value)||'template',parseMode:'HTML',brandName:(q('templateBrand')&&q('templateBrand').value.trim())||null,header:(q('templateHeader')&&q('templateHeader').value.trim())||null,footer:(q('templateFooter')&&q('templateFooter').value.trim())||null,disclaimer:null,cleanupRules:{},layout:{aiInstructions:instructions||null}};try{await admin('/api/v1/admin/templates',{method:'POST',body:JSON.stringify(payload)});note('Formatting template saved.','success');if(q('aiPresentationPrompt'))q('aiPresentationPrompt').value='';if(q('refreshBtn'))q('refreshBtn').click();setTimeout(refreshLifecyclePanels,450)}catch(e){note('Template failed: '+String(e.message||e),'error')}})}
function mapById(rows){var out={};(rows||[]).forEach(function(x){if(x&&x.id)out[String(x.id)]=x});return out}
function button(label,attr,id,kind,extra){return '<button class="btn '+(kind||'secondary')+'" '+attr+'="'+esc(id)+'" '+(extra||'')+'>'+esc(label)+'</button>'}
async function refreshLifecyclePanels(){var d=q('enterpriseDestinationControlRows'),r=q('enterpriseRouteControlRows');if(!d&&!r)return;try{var jobs=await Promise.all([admin('/api/v1/admin/sources'),admin('/api/v1/admin/destinations'),admin('/api/v1/admin/logical-routes')]);var sources=jobs[0].sources||[],destinations=jobs[1].destinations||[],routes=jobs[2].logicalRoutes||[],sourceById=mapById(sources),destinationById=mapById(destinations);window.__mketyLogicalRouteRows=routes;if(d)d.innerHTML=destinations.length?destinations.map(function(x){return '<div class="toolbar" data-completion-managed="1" style="border-top:1px solid #e8edf4;padding:8px 0"><div><b>'+esc(x.displayName||'Destination')+'</b><div class="muted small">'+esc(x.destinationType)+' • '+esc(x.enabled?'Enabled':'Disabled')+'</div></div><div class="actions">'+button(x.enabled?'Disable':'Enable','data-completion-destination-toggle',x.id,'secondary','data-enable="'+(x.enabled?'0':'1')+'"')+button('Remove','data-destination-remove',x.id,'danger')+'</div></div>'}).join(''):'<div class="empty" data-completion-managed="1">No destinations yet.</div>';if(r)r.innerHTML=routes.length?routes.map(function(x){var s=sourceById[String(x.sourceConnectionId)]||{},dest=destinationById[String(x.destinationId)]||{},sourceName=s.displayName||s.sourceInstanceId||'Unknown source',destName=dest.displayName||'Unknown destination',destState=dest.id?(dest.enabled?'':' • destination disabled'):' • destination missing',scope=x.mode==='all'?'All channels':String((x.selectedFeedIds||[]).length)+' selected';return '<div class="toolbar" data-completion-managed="1" style="border-top:1px solid #e8edf4;padding:8px 0"><div><b>'+esc(x.routeName||'Route')+'</b><div class="muted small">'+esc(sourceName)+' → '+esc(destName)+' • '+esc(scope)+' • '+esc(x.enabled?'Enabled':'Disabled')+esc(destState)+'</div></div><div class="actions">'+button(x.enabled?'Disable':'Enable','data-completion-logical-route-toggle',x.logicalRouteKey,'secondary','data-enable="'+(x.enabled?'0':'1')+'"')+button('Remove','data-logical-route-remove',x.logicalRouteKey,'danger')+'</div></div>'}).join(''):'<div class="empty" data-completion-managed="1">No routes yet.</div>'}catch(e){note('Routing controls could not refresh: '+String(e.message||e),'error')}}
function logicalRoute(key){return (window.__mketyLogicalRouteRows||[]).find(function(x){return x.logicalRouteKey===key})||null}
function logicalPayload(x,enabled){return{sourceConnectionId:x.sourceConnectionId,destinationId:x.destinationId,previousSourceConnectionId:x.sourceConnectionId,previousDestinationId:x.destinationId,previousRouteIds:x.routeIds||[],mode:x.mode,selectedFeedIds:x.mode==='all'?[]:(x.selectedFeedIds||[]),routeName:x.routeName||null,priority:Number(x.priority==null?100:x.priority),enabled:enabled,filters:x.filters||{}}}
async function removeDestination(id){if(!window.confirm('Remove this destination permanently? Any routes that point to it will also be removed.'))return;try{await admin('/api/v1/admin/destinations/'+encodeURIComponent(id),{method:'DELETE'});note('Destination removed.','success');if(q('refreshBtn'))q('refreshBtn').click();setTimeout(refreshLifecyclePanels,350)}catch(e){note('Destination removal failed: '+String(e.message||e),'error')}}
async function removeLogicalRoute(key){var x=logicalRoute(key);if(!x)return;if(!window.confirm('Remove this logical route permanently? Every selected feed row in this route will be removed together.'))return;try{await admin('/api/v1/admin/logical-routes/reconcile',{method:'DELETE',body:JSON.stringify({sourceConnectionId:x.sourceConnectionId,destinationId:x.destinationId,previousRouteIds:x.routeIds||[]})});note('Route removed.','success');await refreshLifecyclePanels()}catch(e){note('Route removal failed: '+String(e.message||e),'error')}}
async function toggleLogicalRoute(key,enabled){var x=logicalRoute(key);if(!x)return;try{await admin('/api/v1/admin/logical-routes/reconcile',{method:'PATCH',body:JSON.stringify(logicalPayload(x,enabled))});await refreshLifecyclePanels()}catch(e){note('Routing update failed: '+String(e.message||e),'error')}}
async function toggleDestination(id,enabled){try{await admin('/api/v1/admin/destinations/'+encodeURIComponent(id)+'/'+(enabled?'enable':'disable'),{method:'POST',body:'{}'});await refreshLifecyclePanels()}catch(e){note('Routing update failed: '+String(e.message||e),'error')}}
function bindActions(){document.addEventListener('click',function(ev){var t=ev.target&&ev.target.closest&&ev.target.closest('[data-logical-route-remove]');if(t){ev.preventDefault();removeLogicalRoute(t.dataset.logicalRouteRemove);return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-destination-remove]');if(t){ev.preventDefault();removeDestination(t.dataset.destinationRemove);return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-completion-logical-route-toggle]');if(t){ev.preventDefault();toggleLogicalRoute(t.dataset.completionLogicalRouteToggle,t.dataset.enable==='1');return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-completion-destination-toggle]');if(t){ev.preventDefault();toggleDestination(t.dataset.completionDestinationToggle,t.dataset.enable==='1');return}t=ev.target&&ev.target.closest&&ev.target.closest('[data-source-toggle],[data-account-active],[data-account-execution],[data-account-kill]');if(t)setTimeout(refreshLifecyclePanels,350)})}
function observeEnterprisePanels(){['enterpriseDestinationControlRows','enterpriseRouteControlRows'].forEach(function(id){var el=q(id);if(!el)return;var observer=new MutationObserver(function(){var first=el.firstElementChild;if(first&&first.getAttribute('data-completion-managed')==='1')return;setTimeout(refreshLifecyclePanels,0)});observer.observe(el,{childList:true})})}
function init(){ensureAiPromptField();replaceTemplateCreate();bindActions();setTimeout(function(){refreshLifecyclePanels();observeEnterprisePanels()},500);setTimeout(refreshLifecyclePanels,1900);var refresh=q('refreshBtn');if(refresh)refresh.addEventListener('click',function(){setTimeout(refreshLifecyclePanels,450)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();</script>`;
  return String(html).replace('</body>', `${script}</body>`);
}
