name = "mkety-copier-engine"
main = "src/v1_entry.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "MTPROTO_LISTENER_NAMESPACE", class_name = "MTProtoListenerNode" },
  { name = "TRADE_STATE_NAMESPACE", class_name = "TradeStateNode" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MTProtoListenerNode"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["TradeStateNode"]

[triggers]
crons = ["*/15 * * * *"]
